# Numpy Library
- Numerical Python 
- homogenous data-structures
- multi-dimensional

In [1]:
import numpy as np

In [3]:
ht = [1.73, 1.89, 1.66]

In [2]:
wt = [55,65, 68]

In [4]:
bmi = wt/ht**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [6]:
list(zip(ht, wt))

[(1.73, 55), (1.89, 65), (1.66, 68)]

In [11]:
z = zip(ht, wt)

In [12]:
list(map(lambda x: x[1]/x[0]**2, z))

[18.376825152861773, 18.19657904313989, 24.677021338365513]

In [13]:
import numpy as np

In [15]:
h = np.array(ht)
h

array([1.73, 1.89, 1.66])

In [18]:
w = np.array(wt)
w

array([55, 65, 68])

In [19]:
#numpy arrays support element-wise numerical operations

In [20]:
w/h**2

array([18.37682515, 18.19657904, 24.67702134])

In [21]:
type(h)

numpy.ndarray

In [23]:
h.ndim, w.ndim

(1, 1)

In [25]:
h.shape, w.shape

((3,), (3,))

In [26]:
h.size #size means total number of elements in the array

3

In [28]:
### create a 2-d array
arr = np.array([ht,wt])
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [35]:
type(arr)

numpy.ndarray

In [37]:
ht, wt

([1.73, 1.89, 1.66], [55, 65, 68])

In [30]:
twod_arr = np.array([[1,2,3],[10,20,30]])
twod_arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [33]:
arr.shape, arr.ndim, arr.size

((2, 3), 2, 6)

In [34]:
print(arr)

[[ 1.73  1.89  1.66]
 [55.   65.   68.  ]]


In [42]:
### 3 D array
x = [[[1,2,3], [4,5,6]], [[10,30,50], [100,30, 90]]]
arr = np.array(x)
print(arr)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  30  50]
  [100  30  90]]]


In [43]:
arr.shape #2 sheets with 2 rows and 3 colums

(2, 2, 3)

In [45]:
arr.size  #2*2*3

12

In [50]:
r = np.array([1,3,4,"a"])
r #character array - internal type-casting to a superior data-type 
#char > float > int > bool

array(['1', '3', '4', 'a'], dtype='<U21')

In [52]:
### create a 2-d array
arr = np.array([ht,wt])
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [53]:
arr.flatten()

array([ 1.73,  1.89,  1.66, 55.  , 65.  , 68.  ])

In [56]:
arr.transpose()

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 68.  ]])

In [57]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [59]:
arr[0,:] #row number 0

array([1.73, 1.89, 1.66])

In [60]:
arr[1,:]

array([55., 65., 68.])

In [61]:
arr[0,0]

1.73

In [62]:
arr[0,2 ]

1.66

In [63]:
arr[:,0]

array([ 1.73, 55.  ])

In [64]:
arr[:,1]

array([ 1.89, 65.  ])

In [65]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [66]:
arr[:1, :2] #list slicing rules will be applicable for row slicing and column slicing

array([[1.73, 1.89]])

In [67]:
arr[-1, -1]

68.0

In [68]:
arr[::-1, ::-1]

array([[68.  , 65.  , 55.  ],
       [ 1.66,  1.89,  1.73]])

In [70]:
arr[::-1,2::-1]

array([[68.  , 65.  , 55.  ],
       [ 1.66,  1.89,  1.73]])

In [71]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [72]:
arr.dtype

dtype('float64')

In [73]:
h.dtype

dtype('float64')

In [78]:
arr = np.array([1,3,4,100,1000, 100, 300, 500, 999, 1200, 1203, 4500, 5320, 1435, 9245, 1000])

In [79]:
arr.dtype

dtype('int64')

In [80]:
arr.prod()

7408745467841871872

In [81]:
arr.dtype

dtype('int64')

In [82]:
arr = arr.astype("float64")

In [83]:
arr.dtype

dtype('float64')

In [84]:
arr.prod()

8.244566576160844e+39

In [85]:
arr = np.array([1,3,4,100,1000, 100, 300, 500, 999, 1200, 1203, 4500, 5320, 1435, 9245, 1000], dtype = "float64")

In [86]:
arr.dtype

dtype('float64')

In [88]:
x=np.array([])
x

array([], dtype=float64)

In [ ]:
np.int8 - 2^8 values = 256 = -128 to 127

In [ ]:
np.int16 =  2^16 values

In [89]:
arr.astype(np.float64)

array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
       3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
       5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03])

In [90]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.zeros((3,))

array([0., 0., 0.])

In [92]:
np.full((2,3,4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [93]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.eye(4,3, k =-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [102]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [104]:
list(range(100, 20, -10))

[100, 90, 80, 70, 60, 50, 40, 30]

In [105]:
np.arange(100,20,-10)

array([100,  90,  80,  70,  60,  50,  40,  30])

In [106]:
arr

array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
       3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
       5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03])

In [107]:
y = arr

In [108]:
arr[0] = 0

In [109]:
arr,y

(array([0.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]),
 array([0.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]))

In [116]:
z = arr.copy()
arr[0]=10000
z, arr

(array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]),
 array([1.000e+04, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]))

In [117]:
w = np.array(arr) #by default, copy = True
id(w), id(arr)

(140294524941776, 140294504160512)

----

### Random Number Generation functions