# Numpy Library
- Numerical Python 
- homogenous data-structures
- multi-dimensional

In [1]:
import numpy as np

In [3]:
ht = [1.73, 1.89, 1.66]

In [2]:
wt = [55,65, 68]

In [4]:
bmi = wt/ht**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [6]:
list(zip(ht, wt))

[(1.73, 55), (1.89, 65), (1.66, 68)]

In [11]:
z = zip(ht, wt)

In [12]:
list(map(lambda x: x[1]/x[0]**2, z))

[18.376825152861773, 18.19657904313989, 24.677021338365513]

In [13]:
import numpy as np

In [15]:
h = np.array(ht)
h

array([1.73, 1.89, 1.66])

In [18]:
w = np.array(wt)
w

array([55, 65, 68])

In [19]:
#numpy arrays support element-wise numerical operations

In [20]:
w/h**2

array([18.37682515, 18.19657904, 24.67702134])

In [21]:
type(h)

numpy.ndarray

In [23]:
h.ndim, w.ndim

(1, 1)

In [25]:
h.shape, w.shape

((3,), (3,))

In [26]:
h.size #size means total number of elements in the array

3

In [28]:
### create a 2-d array
arr = np.array([ht,wt])
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [35]:
type(arr)

numpy.ndarray

In [37]:
ht, wt

([1.73, 1.89, 1.66], [55, 65, 68])

In [30]:
twod_arr = np.array([[1,2,3],[10,20,30]])
twod_arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [33]:
arr.shape, arr.ndim, arr.size

((2, 3), 2, 6)

In [34]:
print(arr)

[[ 1.73  1.89  1.66]
 [55.   65.   68.  ]]


In [42]:
### 3 D array
x = [[[1,2,3], [4,5,6]], [[10,30,50], [100,30, 90]]]
arr = np.array(x)
print(arr)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  30  50]
  [100  30  90]]]


In [43]:
arr.shape #2 sheets with 2 rows and 3 colums

(2, 2, 3)

In [45]:
arr.size  #2*2*3

12

In [50]:
r = np.array([1,3,4,"a"])
r #character array - internal type-casting to a superior data-type 
#char > float > int > bool

array(['1', '3', '4', 'a'], dtype='<U21')

In [52]:
### create a 2-d array
arr = np.array([ht,wt])
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [53]:
arr.flatten()

array([ 1.73,  1.89,  1.66, 55.  , 65.  , 68.  ])

In [56]:
arr.transpose()

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 68.  ]])

In [57]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [59]:
arr[0,:] #row number 0

array([1.73, 1.89, 1.66])

In [60]:
arr[1,:]

array([55., 65., 68.])

In [61]:
arr[0,0]

1.73

In [62]:
arr[0,2 ]

1.66

In [63]:
arr[:,0]

array([ 1.73, 55.  ])

In [64]:
arr[:,1]

array([ 1.89, 65.  ])

In [65]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [66]:
arr[:1, :2] #list slicing rules will be applicable for row slicing and column slicing

array([[1.73, 1.89]])

In [67]:
arr[-1, -1]

68.0

In [68]:
arr[::-1, ::-1]

array([[68.  , 65.  , 55.  ],
       [ 1.66,  1.89,  1.73]])

In [70]:
arr[::-1,2::-1]

array([[68.  , 65.  , 55.  ],
       [ 1.66,  1.89,  1.73]])

In [71]:
arr

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 68.  ]])

In [72]:
arr.dtype

dtype('float64')

In [73]:
h.dtype

dtype('float64')

In [78]:
arr = np.array([1,3,4,100,1000, 100, 300, 500, 999, 1200, 1203, 4500, 5320, 1435, 9245, 1000])

In [79]:
arr.dtype

dtype('int64')

In [80]:
arr.prod()

7408745467841871872

In [81]:
arr.dtype

dtype('int64')

In [82]:
arr = arr.astype("float64")

In [83]:
arr.dtype

dtype('float64')

In [84]:
arr.prod()

8.244566576160844e+39

In [85]:
arr = np.array([1,3,4,100,1000, 100, 300, 500, 999, 1200, 1203, 4500, 5320, 1435, 9245, 1000], dtype = "float64")

In [86]:
arr.dtype

dtype('float64')

In [88]:
x=np.array([])
x

array([], dtype=float64)

In [ ]:
np.int8 - 2^8 values = 256 = -128 to 127

In [ ]:
np.int16 =  2^16 values

In [89]:
arr.astype(np.float64)

array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
       3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
       5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03])

In [90]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.zeros((3,))

array([0., 0., 0.])

In [92]:
np.full((2,3,4), 7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [93]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.eye(4,3, k =-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [98]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
list(range(10,20,2))

[10, 12, 14, 16, 18]

In [102]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [104]:
list(range(100, 20, -10))

[100, 90, 80, 70, 60, 50, 40, 30]

In [105]:
np.arange(100,20,-10)

array([100,  90,  80,  70,  60,  50,  40,  30])

In [106]:
arr

array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
       3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
       5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03])

In [107]:
y = arr

In [108]:
arr[0] = 0

In [109]:
arr,y

(array([0.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]),
 array([0.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]))

In [116]:
z = arr.copy()
arr[0]=10000
z, arr

(array([1.000e+00, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]),
 array([1.000e+04, 3.000e+00, 4.000e+00, 1.000e+02, 1.000e+03, 1.000e+02,
        3.000e+02, 5.000e+02, 9.990e+02, 1.200e+03, 1.203e+03, 4.500e+03,
        5.320e+03, 1.435e+03, 9.245e+03, 1.000e+03]))

In [117]:
w = np.array(arr) #by default, copy = True
id(w), id(arr)

(140294524941776, 140294504160512)

### Reshaping the arrays

In [3]:
import numpy as np
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
x = x.reshape((5,4))

In [7]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
x = np.arange(20)
x = x.reshape(1,20)
print(x)
print(x.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
(1, 20)


In [12]:
x = np.arange(20)
x.reshape(1, -1) #-1 will indicate the total number of elements in x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [15]:
x = np.arange(20)
x.reshape(20,1)
x = x.reshape(-1,1)
print(x.shape)
print(x)

(20, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [19]:
x = np.arange(8)
x.reshape(-1, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [27]:
x = np.arange(12)
x = x.reshape(2, 3, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [29]:
x.ndim, x.shape, x.size

(3, (2, 3, 2), 12)

In [24]:
x.reshape((1,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [25]:
x.reshape((-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [26]:
x.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

----

# Class 4

### Random Number Generation functions

In [36]:
import numpy as np

In [39]:
np.random.rand(2,3)

array([[0.5080546 , 0.40447782, 0.48259727],
       [0.03240811, 0.27283023, 0.04440897]])

In [43]:
np.random.randn(2,3,2,4)

array([[[[-0.13904101,  0.80477694, -0.53448986,  0.80389945],
         [ 0.15859543,  0.60568058, -0.33830169, -0.35170669]],

        [[-0.71743263, -2.10993359, -0.53803904,  0.70786633],
         [-0.07657177, -0.1183527 ,  0.94454921, -0.33237768]],

        [[ 0.32723265, -2.89212855, -0.33918348,  0.13351436],
         [ 0.79921352, -0.49730933, -1.1881438 ,  0.64994381]]],


       [[[-0.43513867,  1.20691866, -0.4485971 , -0.47077882],
         [-3.44623197,  1.47375961,  0.47042585, -0.00985296]],

        [[-0.33741967, -0.69674755,  0.42628333,  0.74098499],
         [-0.91810218, -0.23776532, -1.13042816, -0.27974535]],

        [[ 0.90627183, -1.37922376,  0.35945105,  0.68282255],
         [ 0.17871021,  0.35563431,  0.3699838 , -0.11888685]]]])

In [45]:
x = np.random.randint(1,101,100) #100 random integers between 1 and 101 where 1 is included and 101 not included
x

array([ 40,  71,   7,  44,  91,  72,  25,  57,  82,  61,  57,  15,   1,
        42,  25,  13,   1,  64,   2,  83,  30,  44, 100,  93,  95,  11,
        17,  77,  15,  22,  83,  99,  90,  36,  87,  50,  73,   3,  59,
        10,  23,  32,  32,  54,  50,  23,   6,  15,  22,  95,  45,  21,
        93,  65,  73,  96,  99,  23,  61,  90,  97,  91,  59,  16,  66,
        88,  57,  72,  93,  86,  99, 100,  18,  50,  73,  68,  14,  72,
        20,  76,   3,  45,  78,  47,  97,  90,  20,  56,  10,  18,  30,
        16,  23,  61,  94,  87,  95,  89,  58,  86])

In [46]:
x.dtype

dtype('int64')

In [49]:
x = x.astype("float64")
x

array([ 40.,  71.,   7.,  44.,  91.,  72.,  25.,  57.,  82.,  61.,  57.,
        15.,   1.,  42.,  25.,  13.,   1.,  64.,   2.,  83.,  30.,  44.,
       100.,  93.,  95.,  11.,  17.,  77.,  15.,  22.,  83.,  99.,  90.,
        36.,  87.,  50.,  73.,   3.,  59.,  10.,  23.,  32.,  32.,  54.,
        50.,  23.,   6.,  15.,  22.,  95.,  45.,  21.,  93.,  65.,  73.,
        96.,  99.,  23.,  61.,  90.,  97.,  91.,  59.,  16.,  66.,  88.,
        57.,  72.,  93.,  86.,  99., 100.,  18.,  50.,  73.,  68.,  14.,
        72.,  20.,  76.,   3.,  45.,  78.,  47.,  97.,  90.,  20.,  56.,
        10.,  18.,  30.,  16.,  23.,  61.,  94.,  87.,  95.,  89.,  58.,
        86.])

In [50]:
np.random.random(5)

array([0.09495785, 0.8643238 , 0.92821027, 0.58239428, 0.74383523])

In [81]:
np.random.seed(1) #this seed can take any value
np.random.random((5,3)) #the same random numbers will be generated every time
#setting the seed / randomstate will help us replicate the random numbers every time I run the program

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])

In [82]:
from numpy import random

In [96]:
type(random)

module

In [85]:
random.seed(19)
random.randint(1,10,100)

array([6, 3, 9, 4, 5, 3, 9, 7, 3, 6, 2, 7, 3, 8, 8, 1, 8, 8, 5, 6, 6, 8,
       2, 2, 3, 6, 4, 8, 9, 6, 6, 1, 2, 5, 7, 2, 4, 2, 5, 2, 4, 6, 4, 8,
       5, 7, 1, 4, 3, 1, 8, 6, 4, 6, 9, 1, 8, 2, 9, 5, 3, 7, 7, 8, 5, 8,
       2, 1, 4, 5, 7, 7, 4, 6, 8, 5, 6, 5, 4, 2, 5, 4, 7, 9, 5, 4, 7, 4,
       2, 2, 1, 7, 8, 4, 6, 6, 8, 2, 4, 7])

In [88]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [108]:
np.random.shuffle(x)
x

array([ 1,  3,  0, 17, 10, 11, 18, 16,  9, 14, 13,  6, 19,  2, 15,  8,  7,
        4,  5, 12])

In [107]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
-np.sort(-x) #sorting in descending order

----

In [112]:
np.linspace(1, 100, 100, endpoint=True) #evenly spaced numbers

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [115]:
np.linspace(1,200, 100, endpoint=False, retstep=True)

(array([  1.  ,   2.99,   4.98,   6.97,   8.96,  10.95,  12.94,  14.93,
         16.92,  18.91,  20.9 ,  22.89,  24.88,  26.87,  28.86,  30.85,
         32.84,  34.83,  36.82,  38.81,  40.8 ,  42.79,  44.78,  46.77,
         48.76,  50.75,  52.74,  54.73,  56.72,  58.71,  60.7 ,  62.69,
         64.68,  66.67,  68.66,  70.65,  72.64,  74.63,  76.62,  78.61,
         80.6 ,  82.59,  84.58,  86.57,  88.56,  90.55,  92.54,  94.53,
         96.52,  98.51, 100.5 , 102.49, 104.48, 106.47, 108.46, 110.45,
        112.44, 114.43, 116.42, 118.41, 120.4 , 122.39, 124.38, 126.37,
        128.36, 130.35, 132.34, 134.33, 136.32, 138.31, 140.3 , 142.29,
        144.28, 146.27, 148.26, 150.25, 152.24, 154.23, 156.22, 158.21,
        160.2 , 162.19, 164.18, 166.17, 168.16, 170.15, 172.14, 174.13,
        176.12, 178.11, 180.1 , 182.09, 184.08, 186.07, 188.06, 190.05,
        192.04, 194.03, 196.02, 198.01]), 1.99)

In [117]:
np.set_printoptions(precision = 1)
np.random.rand(19)

array([0.6, 0.4, 0.4, 0.6, 0.1, 0.2, 0.4, 0.6, 0.4, 0. , 0.5, 0.1, 0.1,
       0.2, 0.7, 0.2, 0.2, 0.4, 0.2])

In [129]:
random.seed(10)
np.set_printoptions(suppress = True)
np.random.randn(100)

array([ 1.3,  0.7, -1.5, -0. ,  0.6, -0.7,  0.3,  0.1,  0. , -0.2,  0.4,
        1.2, -1. ,  1. ,  0.2,  0.4, -1.1,  0.1,  1.5, -1.1, -2. , -1.7,
        0.3,  2.4,  1.1,  1.7,  0.1,  1.4, -0.3,  0.6, -0.3, -0.5,  0.1,
       -0.5,  1.3,  0.2,  0.4, -0.3,  1.3, -0.7,  0.7, -0.4, -0.9, -0.5,
       -0.8, -0.2, -0.3,  0.3,  0.6, -0.1, -0. ,  0.3, -0.5,  0.7,  0.8,
        0.2,  2.4,  0.9, -0.1, -0.4, -0.2, -0.5,  1.1, -0.7, -0.1, -0.5,
        1. , -1.4, -0.4, -0.1,  0.3,  0.5, -0.2,  1. ,  0.3,  2.5, -1.5,
        0.6, -1. , -0.8,  2. ,  1.7, -1.9, -0.2, -0.1, -2.1, -0. ,  0.4,
        0.2, -2. ,  1.1,  0.2, -0.1, -0.8,  0.7,  0.9, -0.5,  0.1,  0.8,
       -2. ])

### Array Indexing

In [131]:
x  = np.random.randn(20)
x

array([-0.6, -1.3,  1.2,  2.5,  1.4,  0.3,  1. ,  0.2,  1.7,  0.7, -0.2,
       -1.1, -0.6,  0.3, -1.2, -0.2,  1.3,  0. ,  2. ,  1.4])

In [134]:
x = x.reshape((5,4))
x

array([[-0.6, -1.3,  1.2,  2.5],
       [ 1.4,  0.3,  1. ,  0.2],
       [ 1.7,  0.7, -0.2, -1.1],
       [-0.6,  0.3, -1.2, -0.2],
       [ 1.3,  0. ,  2. ,  1.4]])

In [135]:
x[[1,2,3], [0,1,3]] #result is always a flattened array

array([ 1.4,  0.7, -0.2])

In [137]:
list(zip([1,2,3], [0,1,3]))

[(1, 0), (2, 1), (3, 3)]

In [139]:
x[2,3]=100
x

array([[ -0.6,  -1.3,   1.2,   2.5],
       [  1.4,   0.3,   1. ,   0.2],
       [  1.7,   0.7,  -0.2, 100. ],
       [ -0.6,   0.3,  -1.2,  -0.2],
       [  1.3,   0. ,   2. ,   1.4]])

In [142]:
x[:2, :3] = 10
x

array([[ 10. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7,   0.7,  -0.2, 100. ],
       [ -0.6,   0.3,  -1.2,  -0.2],
       [  1.3,   0. ,   2. ,   1.4]])

In [144]:
x[[2,3,2], [1,2,3]] = 0
x

array([[10. , 10. , 10. ,  2.5],
       [10. , 10. , 10. ,  0.2],
       [ 1.7,  0. , -0.2,  0. ],
       [-0.6,  0.3,  0. , -0.2],
       [ 1.3,  0. ,  2. ,  1.4]])

In [145]:
x.shape

(5, 4)

In [147]:
row_numbers = x.shape[0]
col_numbers = x.shape[1]

In [152]:
rn = np.arange(row_numbers)
cn = np.arange(col_numbers)
random.shuffle(rn)
random.shuffle(cn)

In [155]:
rn = rn[:-1]
rn, cn

(array([0, 2, 4, 3]), array([0, 1, 3, 2]))

In [158]:
list(zip(rn,cn))

[(0, 0), (2, 1), (4, 3), (3, 2)]

In [157]:
x

array([[10. , 10. , 10. ,  2.5],
       [10. , 10. , 10. ,  0.2],
       [ 1.7,  0. , -0.2,  0. ],
       [-0.6,  0.3,  0. , -0.2],
       [ 1.3,  0. ,  2. ,  1.4]])

In [156]:
x[rn,cn]

array([10. ,  0. ,  1.4,  0. ])

In [159]:
x[rn,cn]+=100

In [160]:
x

array([[110. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7, 100. ,  -0.2,   0. ],
       [ -0.6,   0.3, 100. ,  -0.2],
       [  1.3,   0. ,   2. , 101.4]])

### Boolean Indexing

In [161]:
x>100

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [162]:
x[x>100] #result is a flattened array

array([110. , 101.4])

In [163]:
x[x>100]+=500

In [164]:
x

array([[610. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7, 100. ,  -0.2,   0. ],
       [ -0.6,   0.3, 100. ,  -0.2],
       [  1.3,   0. ,   2. , 601.4]])

In [166]:
np.where(x>100) #to get the index of trues

(array([0, 4]), array([0, 3]))

In [167]:
np.where(x>100, 1,0)

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [169]:
np.where(x>100, -1, x)

array([[ -1. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7, 100. ,  -0.2,   0. ],
       [ -0.6,   0.3, 100. ,  -0.2],
       [  1.3,   0. ,   2. ,  -1. ]])

In [171]:
x[x<0] = np.NaN

In [172]:
x

array([[610. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7, 100. ,   nan,   0. ],
       [  nan,   0.3, 100. ,   nan],
       [  1.3,   0. ,   2. , 601.4]])

In [179]:
np.isnan(x)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False, False,  True],
       [False, False, False, False]])

In [187]:
np.mean(x[~np.isnan(x)])

86.43555705075157

In [188]:
np.where(np.isnan(x), np.mean(x[~np.isnan(x)]), x)

array([[610. ,  10. ,  10. ,   2.5],
       [ 10. ,  10. ,  10. ,   0.2],
       [  1.7, 100. ,  86.4,   0. ],
       [ 86.4,   0.3, 100. ,  86.4],
       [  1.3,   0. ,   2. , 601.4]])

---

### Universal Functions
A universal fn or ufunc operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting. 
Broadcasting means - a set of arrays are broadcastable to the same shape if:
- the arrays have exactly same shape
- thea arrays have exactly same number of dimensions and the length of each dimension is either a common length or 1
- incase the number of dimensions are not same, the array with the fewer dimensions can have their shapes prepended with a dim of length 1 to satisfy the above property

In [192]:
x = np.arange(6)
x= x.reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [198]:
y = np.linspace(1,10, 6)
y =y.reshape(2,3)
y

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])

In [197]:
x + y

array([[ 1. ,  3.8,  6.6],
       [ 9.4, 12.2, 15. ]])

In [199]:
x + [10,20,30] #broadcasting

array([[10, 21, 32],
       [13, 24, 35]])

In [204]:
z = np.arange(2)
z = z.reshape(-1,1)
z

array([[0],
       [1]])

In [206]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [205]:
x + z

array([[0, 1, 2],
       [4, 5, 6]])

In [207]:
x + 10

array([[10, 11, 12],
       [13, 14, 15]])

In [209]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [212]:
y = np.array([10,20,30,40])
y = y.reshape(-1,1)
y

array([[10],
       [20],
       [30],
       [40]])

In [213]:
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [ ]:
np.divide()
np.subtract()
np.multiply()

### Statistical Functions
mean, median, sum, stdev, min, max, argmin, argmax, iqr

In [216]:
x = np.arange(10)
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [217]:
np.mean(x)

4.5

In [219]:
np.median(x)#middle value
#first arrange all the numbers in the increasing order
#odd number of terms then tn+1/2 is the med
#even number of terms mean(tn/2 + t(n/2+1)) will be the median

4.5

In [220]:
np.std(x)

2.8722813232690143

In [222]:
np.max(x)

9

In [223]:
x.min()

0

In [224]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [225]:
np.argmin(x)

0

In [226]:
np.argmax(x)

9

In [227]:
np.quantile(x, .25)

2.25

In [229]:
np.quantile(x, .999)

8.991

#### Concept of axis
axis = 0 - row ; axis = 1 means columns
But in statistical functions, axis = 0 means reduce fn on rows and axis =1 means reduce fn on columns

In [231]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [230]:
np.sum(x, axis = 0)

array([ 5,  7,  9, 11, 13])

In [232]:
np.mean(x, axis = 0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [233]:
np.quantile(x, q = .25, axis = 0)

array([1.2, 2.2, 3.2, 4.2, 5.2])

In [234]:
np.sum(x, axis = 1)

array([10, 35])

In [236]:
np.median(x, axis = 1)

array([2., 7.])

In [237]:
np.argmax(x, axis = 1)

array([4, 4])

In [239]:
x = np.random.rand(3, 5)

In [240]:
x

array([[0.4, 0.2, 0.8, 0.6, 0.8],
       [0.8, 0.6, 0.8, 0.6, 0. ],
       [0.8, 0.2, 0.5, 0.5, 0.5]])

In [242]:
x.argmax(axis = 1) #for each row, the index of the max value, reduce applied column-wise

array([2, 0, 0])

#### Concatenation of arrays

In [243]:
x = np.random.randn(3,4)
y = np.random.randint(1, 10, (3,4))

In [246]:
print(x,"\n\n",y)

[[-0.3  0.3 -0.3  1.7]
 [-1.  -0.2 -0.7 -0.3]
 [-0.4  0.2  0.3 -1.4]] 

 [[1 1 7 6]
 [8 5 1 1]
 [3 3 2 7]]


In [250]:
z = np.concatenate((x,y), axis = 0)
z

array([[-0.3,  0.3, -0.3,  1.7],
       [-1. , -0.2, -0.7, -0.3],
       [-0.4,  0.2,  0.3, -1.4],
       [ 1. ,  1. ,  7. ,  6. ],
       [ 8. ,  5. ,  1. ,  1. ],
       [ 3. ,  3. ,  2. ,  7. ]])

In [251]:
np.concatenate((x,y), axis = 1)

array([[-0.3,  0.3, -0.3,  1.7,  1. ,  1. ,  7. ,  6. ],
       [-1. , -0.2, -0.7, -0.3,  8. ,  5. ,  1. ,  1. ],
       [-0.4,  0.2,  0.3, -1.4,  3. ,  3. ,  2. ,  7. ]])

In [252]:
x

array([[-0.3,  0.3, -0.3,  1.7],
       [-1. , -0.2, -0.7, -0.3],
       [-0.4,  0.2,  0.3, -1.4]])

In [253]:
y = [1,2,3]

In [254]:
np.c_[x,y]

array([[-0.3,  0.3, -0.3,  1.7,  1. ],
       [-1. , -0.2, -0.7, -0.3,  2. ],
       [-0.4,  0.2,  0.3, -1.4,  3. ]])

In [255]:
np.c_[y,x]

array([[ 1. , -0.3,  0.3, -0.3,  1.7],
       [ 2. , -1. , -0.2, -0.7, -0.3],
       [ 3. , -0.4,  0.2,  0.3, -1.4]])

In [256]:
np.concatenate((x,y), axis = 1)

ValueError: all the input arrays must have same number of dimensions

In [258]:
y = np.reshape(y, (-1,1))
y

array([[1],
       [2],
       [3]])

In [259]:
np.concatenate((x,y), axis = 1)

array([[-0.3,  0.3, -0.3,  1.7,  1. ],
       [-1. , -0.2, -0.7, -0.3,  2. ],
       [-0.4,  0.2,  0.3, -1.4,  3. ]])