In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing, model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [26]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [27]:
# Standarize features
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

- multi_class : str, {‘ovr’, ‘multinomial’}, default: ‘ovr’
If the option chosen is ‘ovr’, then a binary problem is fit for each label. 

- For ‘multinomial’ the loss minimised is the multinomial loss fit across the entire probability distribution, even when the data is binary. ‘multinomial’ is unavailable when solver=’liblinear’. ‘auto’ selects ‘ovr’ if the data is binary, or if solver=’liblinear’, and otherwise selects ‘multinomial’. Choosing to minimize softmax loss. 

In [28]:
clf = LogisticRegression(random_state=0) #default: multi_class will take ovr and solver will take liblinear value

In [29]:
# Create one-vs-rest logistic regression object
clf = LogisticRegression(random_state=0, 
                         multi_class='multinomial', 
                         solver='newton-cg')

In [30]:
# Train model
model = clf.fit(X_std, y)

In [31]:
ypred = model.predict(X_std)
ypred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(y, ypred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  1, 49]], dtype=int64)

In [34]:
# Create new observation
new_observation = [[.5, .5, .5, .5]]

In [35]:
# Predict class
model.predict(new_observation)

array([1])

In [36]:
# View predicted probabilities
model.predict_proba(new_observation)

array([[0.01982536, 0.74491994, 0.2352547 ]])