In [2]:
#why numpy arrays
ht = [1.73, 1.89, 1.66]
wt = [55, 65, 58]
#calculat BMI
#wt/ht**2

In [2]:
wt/(ht**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
bmi = []
for i in range(0, len(ht)):
    bmi.append(wt[i]/(ht[i]**2))

In [4]:
bmi

[18.376825152861773, 18.19657904313989, 21.04804761213529]

In [3]:
import numpy as np

In [4]:
numpy

NameError: name 'numpy' is not defined

In [5]:
np.

<module 'numpy' from 'C:\\Users\\Vaibhav\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [169]:
#dir(np)

In [7]:
type(np)

module

In [10]:
ht,wt

([1.73, 1.89, 1.66], [55, 65, 58])

In [7]:
p = np.array([ht, wt])#by default populated row-wise
p

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 58.  ]])

In [8]:
p = p.T

In [9]:
p

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 58.  ]])

In [10]:
p.shape

(3, 2)

In [11]:
p.ndim

2

In [8]:
p.size

6

In [13]:
q = np.array(ht)
q

array([1.73, 1.89, 1.66])

In [12]:
q.ndim

1

In [14]:
q.shape

(3,)

In [17]:
p

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 58.  ]])

In [15]:
p[:,1]

array([55., 65., 58.])

In [16]:
p[:, 0]

array([1.73, 1.89, 1.66])

In [19]:
bmi = p[:,1]/(p[:,0]**2)
bmi

array([18.37682515, 18.19657904, 21.04804761])

In [20]:
bmi.dtype #by default any float array that I create gets the dtype float64
#and any integer array that I create - it will take the lowest dtype

dtype('float64')

In [22]:
p.dtype

dtype('float64')

In [21]:
a = np.array([[1,3,4], [2,5, 1]])
a

array([[1, 3, 4],
       [2, 5, 1]])

In [22]:
a.dtype

dtype('int32')

In [ ]:
#int32 for integers (unless very high values of integers in which case it will take the def datatype of int64)

In [23]:
float_array = np.array([[23.5, 56.3, 34.1], [12,45,90]])
float_array.dtype #default dtype for float is float64

dtype('float64')

In [ ]:
np.int

In [ ]:
#np.int - check the int dtypes available for numpy arrays
#int 8 supports 2 pow 8 numbers i.e -128 to 127
#int 16 supports 2 pow 16 numbers –32768 to 32767

In [23]:
2**8

256

In [26]:
2**8 #int8 will have 256 values -128 to 127

256

In [ ]:
#np.flo

In [24]:
x =  a[0,:]/a[1,:]

In [30]:
x

array([0.5, 0.6, 4. ])

In [31]:
x.dtype

dtype('float64')

In [32]:
import numpy as np
arr_1 = np.array( [185, 925, 37, 821, 892, 170,
                    305, 610, 300, 402, 91, 460, 
                        819, 290, 104, 424, 290, 577,
                            299,144, 826, 811, 253, 843])
arr_1

array([185., 925.,  37., 821., 892., 170., 305., 610., 300., 402.,  91.,
       460., 819., 290., 104., 424., 290., 577., 299., 144., 826., 811.,
       253., 843.])

In [31]:
float(arr_1.prod()) #the garbage value is being converted to float

826277888.0

In [26]:
arr_1.dtype

dtype('int32')

In [25]:
arr_1.prod()

826277888

In [27]:
arr_1 = arr_1.astype(np.float64)
#or
arr_1 = arr_1.astype('float64')

In [28]:
arr_1.dtype

dtype('float64')

In [29]:
arr_1.prod()

7.981525557047434e+60

In [34]:
#another way to get the correct product
import numpy as np
arr_1 = np.array( [185, 925, 37, 821, 892, 170,
                    305, 610, 300, 402, 91, 460, 
                        819, 290, 104, 424, 290, 577,
                            299,144, 826, 811, 253, 843], dtype = np.float64)
arr_1

array([185., 925.,  37., 821., 892., 170., 305., 610., 300., 402.,  91.,
       460., 819., 290., 104., 424., 290., 577., 299., 144., 826., 811.,
       253., 843.])

In [ ]:
np.int

In [35]:
#to create a 3-d array
x = [[[1,2,3],
      [4,5,6]],
     [[10,20,30],
      [40,50,60]]]
x

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]

In [37]:
y = np.array(x)
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [45]:
arr_1.shape, p.shape, y.shape
#24 values in the uni-dimensional array arr_1
#3 rows and 2 cols in bi-dimensional array p
#2 sheets having 2 rows and 3 cols each in our 3 dimensional array y

#if there is a single value in the shape it means it is a unidimensional array - indicated by a single []


((24,), (3, 2), (2, 2, 3))

In [46]:
arr_1.ndim, p.ndim, y.ndim

(1, 2, 3)

In [47]:
arr_1.size, p.size, y.size

(24, 6, 12)

In [38]:
p

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 58.  ]])

In [39]:
len(p.flatten())

6

In [40]:
p.flatten()

array([ 1.73, 55.  ,  1.89, 65.  ,  1.66, 58.  ])

In [41]:
p.ravel()

array([ 1.73, 55.  ,  1.89, 65.  ,  1.66, 58.  ])

In [42]:
#Creating a 4-d array
t = [[[[1,2, 3],[2,4, 3]],
  [[5,6, 3],[7,8, 3]]],
 [[[1,9, 3],[1,2, 3]],
  [[1,5, 1],[9,0, 1]]]]

In [45]:
t = np.array(t)

In [46]:
t #2 workbooks having 2 sheets each with 2 rows and 3 columns

array([[[[1, 2, 3],
         [2, 4, 3]],

        [[5, 6, 3],
         [7, 8, 3]]],


       [[[1, 9, 3],
         [1, 2, 3]],

        [[1, 5, 1],
         [9, 0, 1]]]])

In [54]:
t.ndim

4

In [47]:
t.shape

(2, 2, 2, 3)

In [27]:
arr_1.prod() #this gives a garbage value

826277888

In [28]:
arr_1.dtype

dtype('int32')

In [3]:
arr_1.prod()

826277888

In [29]:
arr_1 = arr_1.astype(np.float64)
arr_1

array([185., 925.,  37., 821., 892., 170., 305., 610., 300., 402.,  91.,
       460., 819., 290., 104., 424., 290., 577., 299., 144., 826., 811.,
       253., 843.])

In [30]:
arr_1.prod()#the product changes when we type-cast it to a higher data-type

7.981525557047434e+60

In [31]:
arr_1 = arr_1.astype('float64')
arr_1.dtype

dtype('float64')

In [63]:
p.dtype

dtype('float64')

In [64]:
p

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 58.  ]])

In [67]:
p = p.astype(np.int64)
p

array([[ 1,  1,  1],
       [55, 65, 58]], dtype=int64)

In [69]:
#we can also declare the data-type while declaring the array
p = np.array([ht, wt], dtype =np.int64)
p

array([[ 1,  1,  1],
       [55, 65, 58]], dtype=int64)

In [70]:
np.array([])

array([], dtype=float64)

In [ ]:
#arrays are always homogenous datastructure - same data-type

In [48]:
r = np.array([1,3,4,'a'])

In [49]:
r.shape

(4,)

In [73]:
r.size

4

In [74]:
r.ndim

1

In [50]:
r.dtype

dtype('<U11')

In [51]:
r

array(['1', '3', '4', 'a'], dtype='<U11')

In [ ]:
#char>float>int>bool
#char + float -> char (internal typecasting)
#bool+int -> int
#float+bool ->float array

In [58]:
a = np.zeros(shape = (2,3))
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
b = a #it creates a shallow copy

In [60]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
b[1,1] = 100
b

array([[  0.,   0.,   0.],
       [  0., 100.,   0.]])

In [64]:
a

array([[  0.,   0.,   0.],
       [  0., 100.,   0.]])

In [65]:
id(a), id(b)

(2111566580192, 2111566580192)

In [66]:
b = a.copy()
id(a), id(b)

(2111566580192, 2111559512112)

In [68]:
a[1,2] = 100
print(a)
print()
print(b)

[[  0.   0.   0.]
 [  0. 100. 100.]]

[[  0.   0.   0.]
 [  0. 100.   0.]]


In [70]:
b = np.array(a)
print(a)
print()
print(b)

[[  0.   0.   0.]
 [  0. 100. 100.]]

[[  0.   0.   0.]
 [  0. 100. 100.]]


In [71]:
id(a), id(b)

(2111566580192, 2111559514832)

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.full((3,2,2),7, dtype = np.float64)

array([[[7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.]],

       [[7., 7.],
        [7., 7.]]])

In [72]:
np.eye(3) #square matrix of shape 3 X 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [78]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1, 100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [87]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
### Random number generation
import numpy as np

In [79]:
from numpy import random

In [80]:
from numpy import *

In [81]:
def add(a,b):
    return a+b

In [82]:
add(4,5)

9

In [90]:
np.random.rand(2,3)

array([[0.47702196, 0.17743105, 0.41501262],
       [0.84496306, 0.26704024, 0.2440836 ]])

In [ ]:
#random numbers from a standard normal distributions

In [91]:
np.random.randn(3) #random numbers following a normal distrib with mean = 0 and std devn = 1

array([-0.42967742, -0.04049918,  1.62333051])

In [16]:
np.random.randn(2,3,2)

array([[[-0.11187856,  0.79286133],
        [ 0.69408655,  0.5308205 ],
        [ 0.45578121,  0.83137166]],

       [[ 0.22933151, -0.21303832],
        [-0.0995113 ,  0.04982399],
        [-0.28248149, -1.27620361]]])

In [ ]:
#to generate random integers

In [19]:
np.random.randint(1, 100, size = 10)

array([98, 76, 81, 93, 91, 74,  6, 15, 75,  6])

In [ ]:
np.random.randint(1, 100, size = (2,3))

In [20]:
#to generate random numbers of specified shape
np.random.random((2,3))

array([[0.35054719, 0.27405275, 0.14068256],
       [0.59734766, 0.61261873, 0.21908352]])

In [68]:
np.random.seed(5) #any number of your choice
#seed will help us in replicating the output of the random number generator, 
#if we don't put the seed, then everytime different random numbers are generated
np.random.random(10)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [22]:
import random

In [23]:
random.seed(56)

In [63]:
a = list(np.arange(1,100,2))
random.shuffle(a)
print(a)

[57, 29, 97, 1, 23, 91, 51, 87, 77, 59, 63, 11, 35, 47, 71, 13, 15, 25, 95, 41, 37, 49, 55, 75, 9, 33, 85, 89, 31, 45, 43, 99, 5, 3, 67, 19, 73, 93, 21, 17, 53, 83, 7, 27, 79, 39, 69, 81, 61, 65]


In [47]:
np.random.seed(2)
np.random.random(10)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728])

In [66]:
#sequence from 1:200
print(list(range(1,200)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199]


In [68]:
np.arange(1,200)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [69]:
np.linspace(1,200, 200, endpoint=True) #this will generate numbers from 1 to 200 in lin space
#linspace generates equidistant numbers

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [80]:
import numpy as np
a = np.linspace(0,1,9)
a

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [81]:
a = a.reshape(3,3)  
a

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

### Indexing

In [82]:
#integer indexing
a[1,1]

0.5

In [87]:
b = a.copy()

In [92]:
c = np.array(a)
id(c), id(a)

(1942482585280, 1942486143504)

In [89]:
a[2,0] = 10
print(a[2,0])
print(a)

10.0
[[ 0.     0.125  0.25 ]
 [ 0.375  0.5    0.625]
 [10.     0.875  1.   ]]


In [90]:
b

array([[ 0.   ,  0.125,  0.25 ],
       [ 0.375,  0.5  ,  0.625],
       [20.   ,  0.875,  1.   ]])

In [5]:
#slicing the rows and columns using :
a[1,:]

array([0.375, 0.5  , 0.625])

In [6]:
a[1:2, 1:] #retrieves 1st row and 1st column to all the cols

array([[0.5  , 0.625]])

In [7]:
#we can mix integer indexing and slicing in numpy arrays
a[:,1]

array([0.125, 0.5  , 0.875])

In [94]:
a

array([[ 0.   ,  0.125,  0.25 ],
       [ 0.375,  0.5  ,  0.625],
       [10.   ,  0.875,  1.   ]])

In [95]:
a[::-1, :]

array([[10.   ,  0.875,  1.   ],
       [ 0.375,  0.5  ,  0.625],
       [ 0.   ,  0.125,  0.25 ]])

In [93]:
a[-1:-2:-1, :]

array([[10.   ,  0.875,  1.   ]])

In [101]:
a[-1:-2:-1, :] = [1000,2000,3000]

In [103]:
np.set_printoptions(suppress=True) 
a

array([[   0.   ,    0.125,    0.25 ],
       [   0.375,    0.5  ,    0.625],
       [1000.   , 2000.   , 3000.   ]])

In [ ]:
####Array indexing or indexing using lists

In [13]:
a[[0,0],[1,2]] #a[0,1] and a[0,2]

array([0.125, 0.25 ])

In [104]:
list(zip([0,0],[1,2]))

[(0, 1), (0, 2)]

In [105]:
a.shape

(3, 3)

In [107]:
row_numbers = np.arange(a.shape[0])
row_numbers

array([0, 1, 2])

In [113]:
import random
col_numbers = [0,1,2]
random.seed(10)
random.shuffle(col_numbers)
print(row_numbers)
print(col_numbers)


[0 1 2]
[1, 0, 2]


In [114]:
a[row_numbers, col_numbers]

array([   0.125,    0.375, 3000.   ])

In [29]:
np.set_printoptions(suppress=True) 
#to suppress the scientific notations
a

array([[  0.   ,   0.125,   0.25 ],
       [  0.375,   0.5  ,   0.625],
       [100.   , 200.   , 300.   ]])

In [20]:
list(zip(row_numbers, col_numbers))

[(0, 1), (1, 2), (2, 0)]

In [21]:
row_numbers = [0,1]
col_numbers = np.arange(a.shape[1])

In [110]:
a[row_numbers, col_numbers]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [111]:
#to make modifications in the array using list / array indexing
row_numbers = np.arange(a.shape[0])
row_numbers

array([0, 1, 2])

In [124]:
col_numbers = [0,1,2]
random.seed(10)
random.shuffle(col_numbers)
print(row_numbers)
print(col_numbers)


[0 1 2]
[1, 0, 2]


In [126]:
a

array([[ 200.   ,    0.125,    0.25 ],
       [   0.375,    0.5  ,  200.625],
       [1000.   , 2200.   , 3000.   ]])

In [127]:
a[row_numbers, col_numbers]+=100

In [128]:
a

array([[ 200.   ,  100.125,    0.25 ],
       [ 100.375,    0.5  ,  200.625],
       [1000.   , 2200.   , 3100.   ]])

In [ ]:
#Boolean Indexing

In [129]:
a>100

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [117]:
a[a>100] #the result is a flattened array

array([100.5, 200. , 400. ])

In [135]:
a[np.logical_or(a>100,a<300)]

array([1200.   ,  100.125,    0.25 ,  100.375,    0.5  ,  200.625,
       2000.   , 3200.   , 4100.   ])

In [131]:
a[(a>100) & (a<300)]

array([200.   , 100.125, 100.375, 200.625])

In [ ]:
#| #either x is true or y is true

In [132]:
a

array([[ 200.   ,  100.125,    0.25 ],
       [ 100.375,    0.5  ,  200.625],
       [1000.   , 2200.   , 3100.   ]])

In [133]:
#the benefit of boolean indexing is that it can be used to modify the array
a[a%2==0]+=1000

In [134]:
a

array([[1200.   ,  100.125,    0.25 ],
       [ 100.375,    0.5  ,  200.625],
       [2000.   , 3200.   , 4100.   ]])

In [ ]:
#np.where command

In [127]:
x_1 = np.array([1,2,3,4,5])
y_1=np.array([11,22,33, 44,55])

In [129]:
out = np.where(x_1%2==0)
out #the indexes where the condition is being satisfied

(array([1, 3], dtype=int64),)

In [131]:
out = np.where(x_1%2==0, x_1, y_1)
out

array([11,  2, 33,  4, 55])

In [133]:
np.random.seed(1)
mat = np.random.randint(1,10,25)
mat.reshape(5,5)

array([[6, 9, 6, 1, 1],
       [2, 8, 7, 3, 5],
       [6, 3, 5, 3, 5],
       [8, 8, 2, 8, 1],
       [7, 8, 7, 2, 1]])

In [134]:
np.where(mat>5) #indexes where the condition is satisfied

(array([ 0,  1,  2,  6,  7, 10, 15, 16, 18, 20, 21, 22], dtype=int64),)

In [136]:
np.where(mat>5, True,False)

array([ True,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False, False, False,  True,  True, False,
        True, False,  True,  True,  True, False, False])

----

In [ ]:
#Universal functions

#A universal function (or ufunc for short) is a function 
#that operates on ndarrays in an element-by-element fashion, 
#supporting array broadcasting, type casting, and several 
#other standard features. That is, a ufunc is a “vectorized” 
#wrapper for a function that takes a fixed number of specific 
#inputs and produces a fixed number of specific outputs.

#Broadcasting
#A set of arrays is called “broadcastable” to the same shape if the above rules produce a valid result, i.e., one of the following is true:

    The arrays all have exactly the same shape.
    The arrays all have the same number of dimensions and the length of each dimensions is either a common length or 1.
    The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

In [137]:
# Array Maths
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x,"\n,\n", y)

[[1 2]
 [3 4]] 
,
 [[5 6]
 [7 8]]


In [138]:
# Element wise Addition
print(x + y)
print(np.add(x, y)) 
#note add is an instance of ufunc class i.e it can be broadcasted or type casted

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [139]:
x

array([[1, 2],
       [3, 4]])

In [35]:
#elaborating broadcasting
x+5 #notice 5 gets added to all the components of x

array([[6, 7],
       [8, 9]])

In [36]:
x+[1,2] #notice that the row [1,2] gets added to each of the rows in matrix x

array([[2, 4],
       [4, 6]])

In [39]:
p = [[1], [2]]
p = np.array(p)
print(p)
print(p.shape)
#p array can be also achieved through reshape
#after explaining reshape - we'll demonstrate 1 more app of broadcasting

[[1]
 [2]]
(2, 1)


In [40]:
print(x)
print(x+p)

[[1 2]
 [3 4]]
[[2 3]
 [5 6]]


In [60]:
#To convert a 1-d array to a 2-d array
p = np.linspace(1,20,10)
p

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [61]:
p.shape, p.ndim

((10,), 1)

In [62]:
#if i want all the numbers in rows and 1 col
q= p.reshape(-1, 1) #number of rows will be equal to total length of the array
q

array([[ 1.        ],
       [ 3.11111111],
       [ 5.22222222],
       [ 7.33333333],
       [ 9.44444444],
       [11.55555556],
       [13.66666667],
       [15.77777778],
       [17.88888889],
       [20.        ]])

In [63]:
#what if I want no. of rows = 1 and no.of cols  = length of the array
p.reshape(1, -1) #this will give 1 row and length of the array as the number of columns

array([[ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]])

In [64]:
a = np.array([1,2]).reshape(-1,1)#reshape to (-1,1) indicates number of rows = length(array) and 1 column
print(a.shape)
print(a)

(2, 1)
[[1]
 [2]]


In [65]:
print(x, "\n\n", x+a) 
#notice 1,2 added to each col

[[1 2]
 [3 4]] 

 [[2 3]
 [5 6]]


In [66]:
import numpy as np
a  = np.linspace(start = 1, stop = 3, num = 3)
print(a)
a = a.reshape(3,1)
a = a.reshape(-1,1) #-1 indicates the length of the array
print(a)

[1. 2. 3.]
[[1.]
 [2.]
 [3.]]


In [67]:
b = a.reshape(1,3)
b = a.reshape(1, -1) #-1 indicates the length of the array
b

array([[1., 2., 3.]])

In [68]:
a+b

array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

a after broadcasting:
- [1,1,1]
- [2,2,2]
- [3,3,3]

b after broadcasting:
- [1,2,3]
- [1,2,3]
- [1,2,3]

In [69]:
# Element wise Subtraction
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [70]:
#Element wise Multiplication
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [71]:
#Element wise Division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


---

In [94]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [97]:
import numpy as np
v = np.array([1,2])
w = np.array([3, 4])

In [98]:
# Dot product of vectors
print(v.dot(w))
print(np.dot(v, w))

11
11


In [75]:
# Matrix product
p = np.array([[1,2,3],[4,5,6]])
q = np.array([[10,20,30], [40,50,60],[100,200,300]])

print(p.dot(q))
print()
print(np.dot(p,q))
print()
print(np.matmul(p,q))

[[ 390  720 1050]
 [ 840 1530 2220]]

[[ 390  720 1050]
 [ 840 1530 2220]]

[[ 390  720 1050]
 [ 840 1530 2220]]


In [76]:
# determine the inner product of two vectors
a1d = np.array([9 , 2 ])
b1d = np.array([10, 5])
print(np.inner(a1d,b1d)) #means 9*10 + 2*5

100


In [77]:
x = np.array([1, 2])   
print(x.dtype)       

int32


In [78]:
y.sum()

26

In [79]:
x = np.array([1.0, 2.0])   
print(x.dtype)             

float64


In [80]:
x = np.array([1, 2], dtype=np.int64)   
print(x.dtype)                         

int64


In [81]:
x = np.array([1, 2], dtype=np.float32)   
print(x.dtype)                 

float32


In [99]:
#array sorting does not work for character arrays
arr = np.array(['Siva','vineet','nitin'] )

In [100]:
#Array sorting does not work for character arrays
arr.sort()
arr

array(['Siva', 'nitin', 'vineet'], dtype='<U6')

In [140]:
y = np.array([20,10, 34, 5])
np.sort(np.array(y))

array([ 5, 10, 20, 34])

In [102]:
#to sort in decreasing order
-y #this will add - to each element of np arrayb

array([-20, -10, -34,  -5])

In [103]:
np.sort(-y)

array([-34, -20, -10,  -5])

In [104]:
-np.sort(-y)

array([34, 20, 10,  5])

In [141]:
sorted(y,reverse = True)

[34, 20, 10, 5]

----

### Statistical Functions

In [140]:
char  = np.array(['a','b', 'd', 'p','c'])

In [139]:
char.max()

TypeError: cannot perform reduce with flexible type

In [142]:
max(char), min(char)

('p', 'a')

In [ ]:
#the reduce operation can be performed only with numerical arrays
#integer or float arrays

In [143]:
y = np.linspace(1, 12, 12)
y = y.reshape(3,4)
y

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [145]:
y.min() #when axis is not mentioned it returns the min value of the array

1.0

In [146]:
y.argmin()

0

In [147]:
y.argmax()

11

In [148]:
y.sum()

78.0

In [145]:
y

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [144]:
y.min(axis = 0)#axis = 0 always represents rows and axis = 1 represents columns
#axis = 0 means the reduce operation has to be performed on the rows, 
#so this will give me min value for each columns

array([1., 2., 3., 4.])

In [151]:
y.max(axis = 1) #reduce operation applied for each column so we get the max value of each row

array([ 4.,  8., 12.])

In [152]:
y.mean(axis = 0) 
#this means that the reduce operation will be performed on rows and we get the col wise mean

array([5., 6., 7., 8.])

In [ ]:
#min, max, mean, sum, argmin, argmax, std, median

---

### Merging the arrays

In [154]:
K  = np.array([[6,19],[33,15]])
M = np.array([[48,6],[22,19]])
print(K,"\n\n", M)

[[ 6 19]
 [33 15]] 

 [[48  6]
 [22 19]]


In [160]:
#vertically stack the 2 array - i.e one over the other
np.vstack((K,M)) #leads to 4 rows and 2 cols

array([[ 6, 19],
       [33, 15],
       [48,  6],
       [22, 19]])

In [161]:
np.hstack((K,M)) #2rows and 4 columns
#means stack the array horizontally

array([[ 6, 19, 48,  6],
       [33, 15, 22, 19]])

#### split the data horizontally and vertically

In [147]:
x = np.linspace(0,100,8)
x

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [148]:
x = x.reshape(2,4)
x

array([[  0.        ,  14.28571429,  28.57142857,  42.85714286],
       [ 57.14285714,  71.42857143,  85.71428571, 100.        ]])

In [150]:
p,q = np.hsplit(x,2) #split the columns into 2 equal halves

In [151]:
p

array([[ 0.        , 14.28571429],
       [57.14285714, 71.42857143]])

In [152]:
q

array([[ 28.57142857,  42.85714286],
       [ 85.71428571, 100.        ]])

In [165]:
np.vsplit(x,2) #vertically split my data

[array([[ 0.        , 14.28571429, 28.57142857, 42.85714286]]),
 array([[ 57.14285714,  71.42857143,  85.71428571, 100.        ]])]

In [155]:
K

array([[ 6, 19],
       [33, 15]])

In [156]:
M

array([[48,  6],
       [22, 19]])

In [166]:
np.concatenate([K,M], axis = 0) #concatenate multiple arrays row-wse 

array([[ 6, 19],
       [33, 15],
       [48,  6],
       [22, 19]])

In [167]:
np.concatenate([K,M], axis = 1)

array([[ 6, 19, 48,  6],
       [33, 15, 22, 19]])

In [157]:
K

array([[ 6, 19],
       [33, 15]])

In [158]:
M = np.array([34, 56])

In [159]:
np.c_[K,M]

array([[ 6, 19, 34],
       [33, 15, 56]])

### Sorting the array

In [41]:
p = np.array([[8,3],
              [3, 9]])
p.sort() #default axis = -1 which means sort along the last axis
print(p) #so columns have been reduced
#We can't sort in descending order

[[3 8]
 [3 9]]


In [ ]:
### Flatten the array

In [160]:
z = np.array([[[[ 0, 1, 2, 3], 
[ 4, 5, 6, 7],
[ 8, 9, 10, 11]], 
[[12, 13, 14, 15],
[ 16, 17, 18, 19],
[ 20, 21, 22, 23]]]])

In [161]:
z.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [162]:
z.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [39]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [2]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print('Set 1 : ', s1)
print('Set 2 : ', s2)

Set 1 :  ['desk' 'chair' 'bulb']
Set 2 :  ['lamp' 'bulb' 'chair']


In [3]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [4]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [5]:
print( np.setdiff1d(s1, s2))# elements in s1 that are not in s2

['desk']


In [ ]:
#to save and load an array

In [163]:
x = np.array([[1,2,3],[4,5,6]])

In [164]:
np.savetxt('array.txt', x)

In [167]:
p = np.loadtxt('array.txt')
p

array([[1., 2., 3.],
       [4., 5., 6.]])

In [168]:
np.save('an_array', x)

In [170]:
q = np.load('an_array.npy')

In [174]:
x = [[[1,2], [3,4]],[[5,6], [7,8]], [[9,10], [11,12]]]

In [175]:
np.array(x)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [177]:
x = np.linspace(1,12,12)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [178]:
x.reshape((3, 2, 2))

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]])