# Numpy Arrays Contd

#### Creation of random numbers

In [1]:
import numpy as np

In [6]:
print(np.random.rand(3))
print()
print(np.random.rand(3,4))

[0.5016496  0.91697356 0.29436415]

[[0.97339812 0.5415587  0.4283862  0.58264799]
 [0.59330098 0.91001811 0.44965286 0.80451856]
 [0.12860759 0.26102633 0.59939687 0.32497111]]


In [7]:
np.random.randn(5)

array([-1.77141726, -0.23860024, -1.8335262 , -0.02450425,  0.52515032])

In [19]:
np.random.seed(10) #seed can be set to any value
#it is used to generate the same random numbers every time we execute it.
#this is required because we want to generate the same random numbers 
#through our program - so as to be able to replicate my results in front of my team /
#in front of my boss / in front of senior management
r = np.random.randn(5,3)
r

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737],
       [-0.96506567,  1.02827408,  0.22863013]])

In [24]:
l = np.random.randint(10,20, 10)
l

array([12, 10, 16, 17, 18, 11, 17, 11, 14, 10])

In [25]:
l.reshape(5,2)

array([[12, 10],
       [16, 17],
       [18, 11],
       [17, 11],
       [14, 10]])

In [23]:
np.random.randint(10,20, (5,2))

array([[19, 11],
       [19, 14],
       [12, 16],
       [17, 18],
       [18, 19]])

In [22]:
np.random.shuffle(r)
r #this is to shuffle the rows of a 2-d array

array([[-0.96506567,  1.02827408,  0.22863013],
       [ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737]])

In [27]:
np.arange(10,200,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [29]:
print(list(range(10,200,10)))

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]


In [31]:
var = np.linspace(1,100,100, endpoint=True) #equidistant numbers
var

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [35]:
x=np.linspace(1,100,20, endpoint=True)
x

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [37]:
x = x.reshape(5,4)
x

array([[  1.        ,   6.21052632,  11.42105263,  16.63157895],
       [ 21.84210526,  27.05263158,  32.26315789,  37.47368421],
       [ 42.68421053,  47.89473684,  53.10526316,  58.31578947],
       [ 63.52631579,  68.73684211,  73.94736842,  79.15789474],
       [ 84.36842105,  89.57894737,  94.78947368, 100.        ]])

In [46]:
np.set_printoptions(suppress = True, precision = 2)
x #precision: uptil 2 decimal places
#suppress: suppress very small values to 0

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11,  58.32],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 84.37,  89.58,  94.79, 100.  ]])

In [49]:
np.array([.05, .06,.0001, .02, .003, .00004])

array([0.05, 0.06, 0.  , 0.02, 0.  , 0.  ])

### Subsetting and slicing

In [82]:
x[2,3] = 100
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11, 100.  ],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 84.37,  89.58,  94.79, 100.  ]])

In [51]:
x[3,1]

68.73684210526315

In [54]:
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11,  58.32],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 84.37,  89.58,  94.79, 100.  ]])

In [56]:
print(x[1])
print(x[0])
print(x[-1]) #last row
print(x[-2]) #2nd last row

[21.84 27.05 32.26 37.47]
[ 1.    6.21 11.42 16.63]
[ 84.37  89.58  94.79 100.  ]
[63.53 68.74 73.95 79.16]


In [61]:
print(x[0:2])
print(x[:2])
print(x[-5:-3])

[[ 1.    6.21 11.42 16.63]
 [21.84 27.05 32.26 37.47]]
[[ 1.    6.21 11.42 16.63]
 [21.84 27.05 32.26 37.47]]
[[ 1.    6.21 11.42 16.63]
 [21.84 27.05 32.26 37.47]]


In [62]:
print(x[2:])
print(x[2:5])
print(x[-3:])

[[ 42.68  47.89  53.11  58.32]
 [ 63.53  68.74  73.95  79.16]
 [ 84.37  89.58  94.79 100.  ]]
[[ 42.68  47.89  53.11  58.32]
 [ 63.53  68.74  73.95  79.16]
 [ 84.37  89.58  94.79 100.  ]]
[[ 42.68  47.89  53.11  58.32]
 [ 63.53  68.74  73.95  79.16]
 [ 84.37  89.58  94.79 100.  ]]


In [63]:
x[::-1]

array([[ 84.37,  89.58,  94.79, 100.  ],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 42.68,  47.89,  53.11,  58.32],
       [ 21.84,  27.05,  32.26,  37.47],
       [  1.  ,   6.21,  11.42,  16.63]])

In [64]:
x[0:4:2] #0th row, 2nd row, 

array([[ 1.  ,  6.21, 11.42, 16.63],
       [42.68, 47.89, 53.11, 58.32]])

In [74]:
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11,  58.32],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 84.37,  89.58,  94.79, 100.  ]])

In [73]:
print(x[:, 0])
print(x[:,1])
print(x[0:2,0])

[ 1.   21.84 42.68 63.53 84.37]
[ 6.21 27.05 47.89 68.74 89.58]
[ 1.   21.84]


In [72]:
print(x[:, 0:2])
print(x[:, :2])
print(x[:, :-2])

[[ 1.    6.21]
 [21.84 27.05]
 [42.68 47.89]
 [63.53 68.74]
 [84.37 89.58]]
[[ 1.    6.21]
 [21.84 27.05]
 [42.68 47.89]
 [63.53 68.74]
 [84.37 89.58]]
[[ 1.    6.21]
 [21.84 27.05]
 [42.68 47.89]
 [63.53 68.74]
 [84.37 89.58]]


In [71]:
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11,  58.32],
       [ 63.53,  68.74,  73.95,  79.16],
       [ 84.37,  89.58,  94.79, 100.  ]])

In [75]:
x[:4:3, ::-1]

array([[16.63, 11.42,  6.21,  1.  ],
       [79.16, 73.95, 68.74, 63.53]])

In [95]:
#slicing can't be used to modify the error
x[-1:-2:-1, :] = [10,20,30] 

ValueError: could not broadcast input array from shape (3) into shape (1,4)

In [86]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

#### Integer Indexing

In [77]:
x[[0,1,2], [0, 2,2]] #retrieves elements (0,0), (1,2) and (2,2) as obtained through the zip operation

array([ 1.  , 32.26, 53.11])

In [79]:
list(zip([0,1,2], [0,2,2]))

[(0, 0), (1, 2), (2, 2)]

In [80]:
x[[-1,-2], [-1,-2]] #-1,-1 and -2,-2

array([100.  ,  73.95])

In [97]:
x[[-1,-2], [-1,-2]] = [4,5]
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,  27.05,  32.26,  37.47],
       [ 42.68,  47.89,  53.11, 100.  ],
       [ 63.53,  68.74,   5.  ,  79.16],
       [ 84.37,  89.58,  94.79,   4.  ]])

In [101]:
x[[0,1,2,3], [0,1,2,3]] #0,0 ; 1,1; 2,2; 3,3

array([ 1.  , 27.05, 53.11, 79.16])

In [102]:
x[[0,1,2,3], [0,1,2,3]] = 1

In [103]:
x

array([[  1.  ,   6.21,  11.42,  16.63],
       [ 21.84,   1.  ,  32.26,  37.47],
       [ 42.68,  47.89,   1.  , 100.  ],
       [ 63.53,  68.74,   5.  ,   1.  ],
       [ 84.37,  89.58,  94.79,   4.  ]])

In [104]:
x[:2]

array([[ 1.  ,  6.21, 11.42, 16.63],
       [21.84,  1.  , 32.26, 37.47]])

#### Boolean Indexing

In [106]:
x>10

array([[False, False,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [108]:
x[x>10] = 10

In [109]:
x #where-ever the values > 10, put it equal to 10

array([[ 1.  ,  6.21, 10.  , 10.  ],
       [10.  ,  1.  , 10.  , 10.  ],
       [10.  , 10.  ,  1.  , 10.  ],
       [10.  , 10.  ,  5.  ,  1.  ],
       [10.  , 10.  , 10.  ,  4.  ]])

In [111]:
np.where(x>=10) #0,2; 0,3; 1,0; 1,2; 1,3; 2,0; 2,1 - where-all the condition yields true

(array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4]),
 array([2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 0, 1, 2]))

In [112]:
b = np.array([1,2,3,4])

In [115]:
np.where(b%2==0) #where-ever the cond is being satisfied, those indices are being retrieved

(array([1, 3]),)

In [117]:
np.where(b%2==0, b, np.nan) #Nan - missing value

array([nan,  2., nan,  4.])

#### Universal Fuctions and Broadcasting
#supports element-wise operation between 2 arrays
- np.add()
- np.subtract()
- np.multiply()
- np.divide()
 A set of arrays are called to be broadcastable to the same shape if one of the following is true:
  - The arrays have exactly same shape
  - The arrays have same number of dimensions and the length of each dimension is either common or it is 1
  - The arrays that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy the above condition

In [ ]:
np.add()

In [ ]:
np.multiply()

In [ ]:
np.subtract()

In [129]:
p = np.array([1,2])
p

array([1, 2])

In [122]:
q = np.array([[10,20],[30,40]])
q

array([[10, 20],
       [30, 40]])

In [124]:
p.shape, q.shape

((2,), (2, 2))

In [125]:
p.ndim

1

In [130]:
r = p.reshape(1,2)

In [131]:
r

array([[1, 2]])

In [132]:
q + r #rows are getting added; r is getting broadcasted to shape 2,2 and it is getting added

array([[11, 22],
       [31, 42]])

In [134]:
print(q)
print()
print(r)

[[10 20]
 [30 40]]

[[1 2]]


In [136]:
q+p 

array([[11, 22],
       [31, 42]])

In [137]:
p.shape #the shape got prepended by 1 - the shape turned into 1,2

(2,)

In [139]:
q+p

array([[11, 22],
       [31, 42]])

In [144]:
print(p)
print("\n")
print(q)

[1 2]


[[10 20]
 [30 40]]


In [142]:
p.reshape(2,1) + q

array([[11, 21],
       [32, 42]])

In [145]:
p

array([1, 2])

In [148]:
s = np.array([10,20])
s

array([10, 20])

In [150]:
s = s.reshape(2,1)
s

array([[10],
       [20]])

In [151]:
p.shape, s.shape

((2,), (2, 1))

In [152]:
p+s

array([[11, 12],
       [21, 22]])

In [153]:
np.add(p,q)

array([[11, 22],
       [31, 42]])

In [154]:
p.shape, q.shape, r.shape, s.shape

((2,), (2, 2), (1, 2), (2, 1))

In [157]:
np.add(p,q)

array([[11, 22],
       [31, 42]])

In [159]:
q = q[:1]

In [160]:
q

array([[10, 20]])

### Statistical Functions
- max, min, sum, mean, median, std, argmax, argmin

In [163]:
y = np.linspace(1,12,12)
y
y =y.reshape(4,3)

In [164]:
y

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [165]:
y.min()

1.0

In [166]:
y.max()

12.0

In [167]:
y.sum()

78.0

In [168]:
y.mean()

6.5

In [169]:
y.argmin()

0

In [170]:
y.argmax()

11

In [ ]:
#axis = 0 - row-wise reduce operation, axis =1 - column wise reduce operation

In [171]:
y

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [172]:
np.sum(y, axis = 0)#rows are being reduced to a single row - which basically means column addn

array([22., 26., 30.])

In [173]:
np.sum(y, axis = 1) #columns are being reduced - which basically means that we got the rows sum

array([ 6., 15., 24., 33.])

In [174]:
y.min(axis = 0)

array([1., 2., 3.])

In [175]:
y.max(axis = 1)

array([ 3.,  6.,  9., 12.])

#### Concatenation of arrays

In [178]:
K = np.array([[10,20],[30,40]])
M = np.array([49, 10])
print(K, "\n\n", M)

[[10 20]
 [30 40]] 

 [49 10]


In [179]:
np.vstack((K,M))

array([[10, 20],
       [30, 40],
       [49, 10]])

In [180]:
np.hstack((K,M))

ValueError: all the input arrays must have same number of dimensions

In [187]:
T=M.reshape((2,1))
T

array([[49],
       [10]])

In [186]:
K.shape, T.shape

((2, 2), (1, 2))

In [189]:
np.hstack((K,T))

array([[10, 20, 49],
       [30, 40, 10]])

In [191]:
M.reshape(-1,1) #this also means the last row and 1 col

array([[49],
       [10]])

In [195]:
print(K, M, T, sep ="\n\n")

[[10 20]
 [30 40]]

[49 10]

[[49]
 [10]]


In [205]:
np.concatenate((K,M), axis = 0)

ValueError: all the input arrays must have same number of dimensions

In [202]:
S = M.reshape(1,-1)
S
S.shape

(1, 2)

In [203]:
S

array([[49, 10]])

In [204]:
np.concatenate((K,S), axis = 0)

array([[10, 20],
       [30, 40],
       [49, 10]])

In [208]:
np.concatenate((K,M.reshape(-1,1)), axis = 1)

array([[10, 20, 49],
       [30, 40, 10]])

In [ ]:
np.c_ #c-class does the concatenation column-wise; the benefit is that I don't have to reshape the uni-dimensional array
#as long as the number of elements is same as the no. of rows, it will concatenate

In [210]:
print(K,M,sep = "\n")

[[10 20]
 [30 40]]
[49 10]


In [211]:
np.c_[K,M]

array([[10, 20, 49],
       [30, 40, 10]])

In [212]:
np.c_[M,K] #I don't have to reshape M array (like in concatenate function)

array([[49, 10, 20],
       [10, 30, 40]])

In [219]:
d = np.linspace(1,100, 10)
d

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [220]:
d.reshape(-1, 1) #10 rows and 1 column

array([[  1.],
       [ 12.],
       [ 23.],
       [ 34.],
       [ 45.],
       [ 56.],
       [ 67.],
       [ 78.],
       [ 89.],
       [100.]])

In [218]:
d.reshape(1,-1)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [225]:
arr1d = np.array([1,2])
arr1d.shape

(2,)

In [233]:
arr1d

array([1, 2])

In [226]:
arr1d.ndim

1

In [229]:
arr2d = arr1d.reshape(1,-1)
arr2d

array([[1, 2]])

In [232]:
arr2d.shape

(1, 2)

In [230]:
p = np.array([[10,20], [30,40]])

In [231]:
np.concatenate((arr2d,p), axis = 0)

array([[ 1,  2],
       [10, 20],
       [30, 40]])

In [234]:
s1 = np.array(["desk", "chair", "bulb"])
s2 = np.array(["lamp", "bulb", "x"])

In [235]:
np.intersect1d(s1, s2)

array(['bulb'], dtype='<U5')

In [236]:
#np.union1d, np.setdiff1d

In [246]:
np.savetxt("fn.txt", p)

In [248]:
t = np.loadtxt("fn.txt")

In [249]:
t

array([[10., 20.],
       [30., 40.]])

In [252]:
I = np.array([0,2,4,5,2,4,0])

In [253]:
np.bincount(I) 
#0 has a freq of 2, 1 has a freq of 0, 2 has freq 2, 3 has a freq of 0, 4 has a freq 2, 5 has a freq of 1

array([2, 0, 2, 0, 2, 1])