In [2]:
import numpy as np

In [5]:
arr = np.array([[2,3,4],[66,7,8]])
arr

array([[ 2,  3,  4],
       [66,  7,  8]])

In [4]:
arr.shape

(2, 3)

In [6]:
arr.ndim

2

In [7]:
a_f = arr.flatten()
a_f

array([ 2,  3,  4, 66,  7,  8])

In [8]:
a_f.ndim

1

In [9]:
a_f.shape

(6,)

In [10]:
a_f.size

6

In [11]:
arr.size

6

In [12]:
a = np.array([[[1,2,3],[4,5,6]], [[10,29,90],[89,23,56]]])

In [13]:
a.shape

(2, 2, 3)

In [14]:
a.size

12

In [15]:
a.ndim

3

In [16]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 29, 90],
        [89, 23, 56]]])

In [17]:
arr

array([[ 2,  3,  4],
       [66,  7,  8]])

In [18]:
arr[0,0]

2

In [19]:
arr[0,1]

3

In [20]:
arr[1,1]

7

In [22]:
arr[1,2]

8

In [23]:
arr[1,0]

66

In [24]:
a[1, 0,0]

10

In [26]:
a_f[2]

4