In [15]:
import numpy as np
import pandas as pd

In [16]:
data = pd.read_csv('pre-process_datasample.csv')

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      9 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [18]:
#Write code to deal with Missing data in  Country Columnn using Pandas
data['Country'].fillna(data.Country.mode()[0],inplace=True)
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8   France  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [19]:
data.Age = data['Age'].replace(np.NaN, data.Age.median())

In [20]:
data.Salary = data.Salary.replace(np.NaN, data.Salary.median())

In [21]:
#Sklearn Expects your data to be in the form of Numpy Array
# .values convert DataFrame into Numpy Array
dataArray = data.values
dataArray

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 61000.0, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.0, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['France', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [22]:
#Sklearn is a stubborn package
#I always expect my data to be numeric, categorical
#Deal with missing values
#Defect - Imputer class only accept numeric columns
#To deal with Categorical Column ---use pandas !!! :)
from sklearn.preprocessing import Imputer
#Object for Numerical Columns - Age, Salary
imputeForNumericColumn = Imputer(missing_values='NaN',
                strategy='mean',
                axis=0)


/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [23]:
#Handle Numerical Missing Value Columns
#fit_transform ---> Calculate the mean and replace NaN with mean for respective column

dataArray[:,[1,2]] = imputeForNumericColumn.fit_transform(dataArray[:,[1,2]])
dataArray

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 61000.0, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.0, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['France', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [35]:
#Deal with Categorical Data
# Country

from sklearn.preprocessing import LabelEncoder #To encode label values
from sklearn.preprocessing import OneHotEncoder #To create dummy variable from label column

encoderCountry = LabelEncoder()
dataArray[:,0] = encoderCountry.fit_transform(dataArray[:,0])
#fit method will only calculate the integral codes
#transform method will make transform the data

dataArray

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [0, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [27]:
from sklearn.preprocessing import LabelEncoder #To encode label values
from sklearn.preprocessing import OneHotEncoder #To create dummy variable from label column

encoderCountry = LabelEncoder()
encoderCountry.fit(dataArray[:,0])
#fit method will only calculate the integral codes
dataArray[:,0] = encoderCountry.transform(dataArray[:,0])
dataArray[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 0, 0], dtype=object)

In [29]:
encoderPurchased = LabelEncoder()
dataArray[:,3] = encoderPurchased.fit_transform(dataArray[:,3])
dataArray

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 61000.0, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.0, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [0, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [42]:
encoderPurchased.classes_

array(['No', 'Yes'], dtype=object)

In [36]:
encoderCountry.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [30]:
dataArray.shape

(10, 4)

In [31]:
#Taking care of Two categorical columns
oheCountry = OneHotEncoder(categorical_features=[0,3])
dataArray = oheCountry.fit_transform(dataArray).toarray()
dataArray

/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 4.0e+01, 6.1e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 1.0e+00, 0.0e+00, 3.8e+01, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 4.8e+01, 7.9e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.7e+01, 6.7e+04]])

In [33]:
dataArray.shape

(10, 7)

In [35]:
df = pd.DataFrame(dataArray, columns = list(encoderCountry.classes_) + list(encoderPurchased.classes_)+['Age', 'Salary'])

In [34]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [36]:
df

France  Germany  Spain   No  Yes   Age   Salary
0     1.0      0.0    0.0  1.0  0.0  44.0  72000.0
1     0.0      0.0    1.0  0.0  1.0  27.0  48000.0
2     0.0      1.0    0.0  1.0  0.0  30.0  54000.0
3     0.0      0.0    1.0  1.0  0.0  38.0  61000.0
4     0.0      1.0    0.0  0.0  1.0  40.0  61000.0
5     1.0      0.0    0.0  0.0  1.0  35.0  58000.0
6     0.0      0.0    1.0  1.0  0.0  38.0  52000.0
7     1.0      0.0    0.0  0.0  1.0  48.0  79000.0
8     1.0      0.0    0.0  1.0  0.0  50.0  83000.0
9     1.0      0.0    0.0  0.0  1.0  37.0  67000.0