In [1]:
import numpy as np

In [2]:
ht = [1.73, 1.89, 1.66]
wt = [55, 66, 58]
bmi_index = wt/(ht**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
bmi = []
for i in range(0, len(ht)):
    bmi.append(wt[i]/ht[i]**2)

In [4]:
bmi

[18.376825152861773, 18.47652641303435, 21.04804761213529]

In [6]:
height = np.array(ht)
height

array([1.73, 1.89, 1.66])

In [8]:
weight = np.array(wt)
weight

array([55, 66, 58])

In [9]:
weight/(height**2)

array([18.37682515, 18.47652641, 21.04804761])

In [11]:
type(height)

numpy.ndarray

In [12]:
height.shape #a uni-dimensional array of shape (3,)

(3,)

In [13]:
height.size #size is total number of elements 

3

In [14]:
height.ndim

1

In [15]:
height.dtype

dtype('float64')

In [18]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
arr.shape

(4, 3)

In [20]:
arr.size

12

In [21]:
arr.ndim

2

In [22]:
arr.dtype

dtype('int64')

In [23]:
### creating a 3-d array

In [25]:
lst = [[[1,2,3], [4,5,6]], [[10,11,12], [13,14,15]]]
lst

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]]]

In [28]:
arr3d = np.array(lst)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [30]:
arr3d.shape # 2 arrays of 2 rows and 3 columns

(2, 2, 3)

In [ ]:
np.int8 #supports 2 pow 8 numbers i.e -128 to 127

In [ ]:
np.int16 #supports 2 pow 16 numbers

In [31]:
arr = np.array([185,190, 925, 1000, 185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000])

In [32]:
arr.dtype

dtype('int64')

In [33]:
arr.prod() #getting a garbage value

-321411986670747648

In [35]:
arr = arr.astype(np.float64)

In [36]:
arr.prod()

3.633584886462238e+52

In [37]:
arr = np.array([185,190, 925, 1000, 185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000], dtype = np.float64)

In [38]:
arr.prod()

3.633584886462238e+52

In [39]:
arr = np.array([185,190, 925, 1000, 185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000,185,190, 925, 1000], dtype = 'float64')

#### Arrays are homogenous in nature

In [40]:
r = [1,3,4,5,'a', 'n', 'p', 10]

In [41]:
np.array(r) #we got a character array (not a numerical array)

array(['1', '3', '4', '5', 'a', 'n', 'p', '10'], dtype='<U21')

In [ ]:
#char>float>int>boolean

### flatten a 2 d array

In [42]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Creation of quick arrays

In [46]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
b = a.copy() #deep and shallow copy concepts

In [48]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.full((4,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.eye(5,10, 3 )

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [54]:
np.arange(5) #similar to range function

array([0, 1, 2, 3, 4])

In [57]:
np.array(list(range(5)))

array([0, 1, 2, 3, 4])

In [58]:
np.arange(100, 2, -3)

array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31,  28,  25,
        22,  19,  16,  13,  10,   7,   4])