In [1]:
#why numpy arrays
ht = [1.73, 1.89, 1.66]
wt = [55, 65, 58]
#calculat BMI
#wt/ht**2

In [2]:
wt/(ht**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [3]:
bmi = []
for i in range(0, len(ht)):
    bmi.append(wt[i]/(ht[i]**2))

In [4]:
bmi

[18.376825152861773, 18.19657904313989, 21.04804761213529]

In [12]:
import numpy as np

In [11]:
numpy.

NameError: name 'numpy' is not defined

In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [7]:
type(np)

module

In [10]:
ht,wt

([1.73, 1.89, 1.66], [55, 65, 58])

In [62]:
p = np.array([ht, wt])#by default populated row-wise
p

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 58.  ]])

In [ ]:
#if we want to get it col wise, transpose it

In [14]:
p.T

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 58.  ]])

In [16]:
p = p.T

In [17]:
p

array([[ 1.73, 55.  ],
       [ 1.89, 65.  ],
       [ 1.66, 58.  ]])

In [19]:
p[:,1], p[:, 0]

(array([55., 65., 58.]), array([1.73, 1.89, 1.66]))

In [20]:
bmi = p[:,1]/(p[:,0]**2)
bmi

array([18.37682515, 18.19657904, 21.04804761])

In [21]:
bmi.dtype #by default any float array that I create gets the dtype float64
#and any integer array that I create - it will take the lowest dtype

dtype('float64')

In [22]:
p.dtype

dtype('float64')

In [24]:
a = np.array([[1,3,4], [2,5, 1]])
a

array([[1, 3, 4],
       [2, 5, 1]])

In [25]:
a.dtype

dtype('int32')

In [ ]:
#np.int - check the int dtypes available for numpy arrays

In [26]:
2**8 #int8 will have 256 values -128 to 127

256

In [ ]:
#np.flo

In [29]:
x =  a[0,:]/a[1,:]

In [30]:
x

array([0.5, 0.6, 4. ])

In [31]:
x.dtype

dtype('float64')

In [2]:
import numpy as np
arr_1 = np.array( [185, 925, 37, 821, 892, 170,
                    305, 610, 300, 402, 91, 460, 
                        819, 290, 104, 424, 290, 577,
                            299,144, 826, 811, 253, 843])
arr_1

array([185, 925,  37, 821, 892, 170, 305, 610, 300, 402,  91, 460, 819,
       290, 104, 424, 290, 577, 299, 144, 826, 811, 253, 843])

In [42]:
#to create a 3-d array
x = [[[1,2,3],
      [4,5,6]],
     [[10,20,30],
      [40,50,60]]]
x

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]

In [43]:
y = np.array(x)
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [45]:
arr_1.shape, p.shape, y.shape
#24 values in the uni-dimensional array arr_1
#3 rows and 2 cols in bi-dimensional array p
#2 sheets having 2 rows and 3 cols each in our 3 dimensional array y

#if there is a single value in the shape it means it is a unidimensional array - indicated by a single []


((24,), (3, 2), (2, 2, 3))

In [46]:
arr_1.ndim, p.ndim, y.ndim

(1, 2, 3)

In [47]:
arr_1.size, p.size, y.size

(24, 6, 12)

In [49]:
len(p.flatten())

6

In [51]:
t = [[[[1,2],[2,4]],
  [[5,6],[7,8]]],
 [[[1,9],[1,2]],
  [[1,5],[9,0]]]]

In [52]:
t = np.array(t)

In [53]:
t

array([[[[1, 2],
         [2, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 9],
         [1, 2]],

        [[1, 5],
         [9, 0]]]])

In [54]:
t.ndim

4

In [55]:
t.shape

(2, 2, 2, 2)

In [3]:
arr_1.prod() #this gives a garbage value

826277888

In [4]:
arr_1.dtype

dtype('int32')

In [8]:
arr_1 = arr_1.astype(np.float64)
arr_1

array([185., 925.,  37., 821., 892., 170., 305., 610., 300., 402.,  91.,
       460., 819., 290., 104., 424., 290., 577., 299., 144., 826., 811.,
       253., 843.])

In [6]:
arr_1.prod()#the product changes when we type-cast it to a higher data-type

7.981525557047434e+60

In [7]:
arr_1 = arr_1.astype('float64')

In [63]:
p.dtype

dtype('float64')

In [64]:
p

array([[ 1.73,  1.89,  1.66],
       [55.  , 65.  , 58.  ]])

In [67]:
p = p.astype(np.int64)
p

array([[ 1,  1,  1],
       [55, 65, 58]], dtype=int64)

In [69]:
p = np.array([ht, wt], dtype = np.int64)
p

array([[ 1,  1,  1],
       [55, 65, 58]], dtype=int64)

In [70]:
np.array([])

array([], dtype=float64)

In [ ]:
#arrays are always homogenous datastructure - same data-type

In [71]:
r = np.array([1,3,4,'a'])

In [72]:
r.shape

(4,)

In [73]:
r.size

4

In [74]:
r.ndim

1

In [75]:
r.dtype

dtype('<U11')

In [76]:
r

array(['1', '3', '4', 'a'], dtype='<U11')

In [ ]:
#char>float>int>bool
#char + float -> char (internal typecasting)
#bool+int -> int
#float+bool ->float array

In [78]:
a = np.zeros((2,3,5))
a
#2 sheets, each having 3 rows and 5 columns

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [81]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [83]:
np.full((3,2,2),7)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [84]:
np.eye(3) #square matrix of shape 3 X 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### Random number generation

In [88]:
np.random.rand(2) #uniform distribution bw 0 and 1

array([0.07726881, 0.58837169])

In [90]:
np.random.rand(2,3)

array([[0.47702196, 0.17743105, 0.41501262],
       [0.84496306, 0.26704024, 0.2440836 ]])

In [ ]:
#random numbers from a standard normal distributions

In [91]:
np.random.randn(3) #random numbers following a normal distrib with mean = 0 and std devn = 1

array([-0.42967742, -0.04049918,  1.62333051])