In [40]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action = "ignore")

In [41]:
location = r"C:\Users\Vaibhav\Desktop\BA\Datasets\iris.csv"

In [42]:
iris = pd.read_csv(location)
iris.head(3)

Unnamed: 0  Species  sepal length (cm)  sepal width (cm)  \
0           0      0.0                5.1               3.5   
1           1      0.0                4.9               3.0   
2           2      0.0                4.7               3.2   

   petal length (cm)  petal width (cm)  
0                1.4               0.2  
1                1.4               0.2  
2                1.3               0.2

In [4]:
iris = iris.drop("Unnamed: 0", 1)

In [5]:
iris["sepal length (cm)"][:3]

0    5.1
1    4.9
2    4.7
Name: sepal length (cm), dtype: float64

In [6]:
iris.columns = ["Species", "sepal_length", "sepal_width", "petal_length", "petal_width"]

In [7]:
iris.head(2)

Species  sepal_length  sepal_width  petal_length  petal_width
0      0.0           5.1          3.5           1.4          0.2
1      0.0           4.9          3.0           1.4          0.2

In [8]:
X = iris.iloc[:,1:]
y = iris.Species

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size = .3, random_state = 2)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [11]:
s = StandardScaler()
s.fit(X_train, y_train)
X_train = s.transform(X_train)
X_test = s.transform(X_test)

In [12]:
knn = KNeighborsClassifier(n_jobs=-1, n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=3, p=2,
                     weights='uniform')

In [13]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': -1,
 'n_neighbors': 3,
 'p': 2,
 'weights': 'uniform'}

In [14]:
ypred = knn.predict(X_test)
ypred

array([0., 0., 2., 0., 0., 2., 0., 2., 2., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 2., 1., 1., 1., 2., 1., 1., 0., 0., 2., 0., 2., 2., 0., 1., 2.,
       1., 0., 2., 1., 1., 2., 1., 1., 2., 1., 0.])

In [15]:
knn.score(X_test, y_test) #accuracy score

1.0

### K-folds
Data divided into k splits of train and test

In [16]:
from sklearn.model_selection import KFold

In [17]:
kf = KFold(n_splits=5, shuffle=True, random_state=2)

In [18]:
kf.split(iris)

<generator object _BaseKFold.split at 0x0000029F61EF7308>

In [19]:
for train_id, test_id in kf.split(iris):
    print(train_id)#train_id will have the row indices of train data in each fold
    print(test_id)
    print("\n")

[  0   1   4   7   8   9  10  11  13  14  15  16  17  18  19  20  21  22
  23  26  27  28  30  31  32  33  34  36  37  38  39  40  43  46  47  49
  50  51  52  53  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  75  76  78  79  80  81  82  83  84  86  88  90  91
  92  93  95  97  98  99 100 101 102 103 104 105 106 107 109 110 111 112
 114 116 117 118 119 120 121 122 123 124 126 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 145 146 147 148 149]
[  2   3   5   6  12  24  25  29  35  41  42  44  45  48  54  74  77  85
  87  89  94  96 108 113 115 125 127 128 129 144]


[  1   2   3   4   5   6   7   8   9  10  12  15  16  17  18  19  21  22
  24  25  26  29  30  31  32  33  34  35  37  38  39  40  41  42  43  44
  45  46  47  48  49  50  51  52  54  55  56  57  58  59  60  61  62  63
  66  67  68  69  70  71  72  73  74  75  76  77  79  80  81  82  83  85
  86  87  88  89  90  92  94  95  96  98  99 100 101 102 103 104 107 108
 109 110 111 112 113 1

# Repeated K-Fold

RepeatedKFold repeats K-Fold n times. It can be used when one requires to run KFold n times, producing different splits in each repetition.

In [20]:
from sklearn.model_selection import RepeatedKFold
random_state = 100
rkf = RepeatedKFold(n_splits=3, n_repeats=2, random_state=random_state)

for train_idx, test_idx in rkf.split(iris):
    print(train_idx)
    print(test_idx)
    print('\n')
#this will generate n_splits X n_repeats splits

[  0   2   3   4   5   7   8  10  13  14  17  18  19  22  23  24  27  30
  33  34  35  36  38  39  42  43  44  47  48  49  50  52  53  54  55  56
  57  58  59  60  61  63  64  65  66  67  68  70  71  72  74  76  78  79
  80  82  83  84  85  86  87  88  91  93  94  95  96  98 100 101 103 104
 105 106 107 108 110 111 113 117 121 124 126 127 129 130 131 132 133 134
 137 138 139 140 141 142 143 144 147 148]
[  1   6   9  11  12  15  16  20  21  25  26  28  29  31  32  37  40  41
  45  46  51  62  69  73  75  77  81  89  90  92  97  99 102 109 112 114
 115 116 118 119 120 122 123 125 128 135 136 145 146 149]


[  1   2   4   6   7   8   9  11  12  14  15  16  19  20  21  24  25  26
  27  28  29  30  31  32  34  37  38  39  40  41  44  45  46  47  48  49
  51  53  55  56  58  59  60  61  62  63  65  66  67  69  71  73  75  77
  79  80  81  86  87  89  90  91  92  93  94  97  98  99 100 102 103 105
 107 108 109 112 114 115 116 118 119 120 121 122 123 125 128 130 135 136
 138 140 141 142 143 1

# Leave One Out (LOO)

- LeaveOneOut (or LOO) is a simple cross-validation. 
- Each learning set is created by taking all the samples except one, the test set being the sample left out. 
- Thus, for n samples, we have n different training sets and n different tests set. 

- This cross-validation procedure does not waste much data as only one sample is removed from the training set:

In [21]:
from sklearn.model_selection import LeaveOneOut
random_state = 100
loocv = LeaveOneOut()
i = 1

for train_idx, test_idx in loocv.split(iris):
    print(train_idx)
    print(test_idx)
    i+=1
    if i==5:
        break
    print('\n')
#this will create 1to n-1 as training and nth sample as test sample
#this way n splits are generated
#displaying only 5 splits

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149]
[0]


[  0   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  9

# Leave P Out (LPO)

LeavePOut is very similar to LeaveOneOut as it creates all the possible training/test sets by removing p  samples from the complete set. 

For n samples, this produces $n \choose p$ train-test pairs. Unlike LeaveOneOut and KFold, the test sets will overlap for  p > 1

In [22]:
from sklearn.model_selection import LeavePOut
lpo = LeavePOut(p=40)

#for train_idx, test_idx in lpo.split(iris):
#    print(train_idx)
#    print(test_idx)

# Stratified K-Folds cross-validator
 Provides train/test indices to split data in train/test sets.

 Parameters:
 n_splits : int, default=3
            Number of folds. Must be at least 2.

 shuffle  : boolean, optional
            Whether to shuffle each stratification of the data before 
            splitting into batches.

 random_state : int, RandomState instance or None, optional, default=None

                If int, random_state is the seed used by the random number 
                generator; 
                If RandomState instance, random_state is the random number 
                generator; 
                if None, the random number generator is the RandomState 
                instance used by np.random. Used when shuffle == True.

In [23]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5, random_state=5)
for train_idx, test_idx in skf.split(iris.iloc[:,1:], iris.Species):
    print(train_idx)
    print(test_idx) #20% rows in test
    print('\n')

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
[  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]


[  0   1   2   3   4   5   6   7   8   9  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 120 121 122 123 124 1

# sklearn.model_selection.ShuffleSplit

Parameters:	
n_splits : int, default 10
Number of re-shuffling & splitting iterations.

test_size : float, int, None, default=0.1
If float, should be between 0.0 and 1.0 and represent the proportion of the dataset to include in the test split. If int, represents the absolute number of test samples. If None, the value is set to the complement of the train size. By default (the parameter is unspecified), the value is set to 0.1. The default will change in version 0.21. It will remain 0.1 only if train_size is unspecified, otherwise it will complement the specified train_size.

train_size : float, int, or None, default=None
If float, should be between 0.0 and 1.0 and represent the proportion of the dataset to include in the train split. If int, represents the absolute number of train samples. If None, the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, optional (default=None)
If int, random_state is the seed used by the random number generator; If RandomState instance, random_state is the random number generator; If None, the random number generator is the RandomState instance used by np.random.

In [24]:
XX = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [3, 4], [5, 6]])
yy = np.array([1, 2, 1, 2, 1, 2])


In [25]:
from sklearn.model_selection import ShuffleSplit
rs = ShuffleSplit(n_splits=5, test_size=.25, random_state=0) 
#nrows = 6 and test size = .25, so test size will be 1.5 i.e 2 and train size:4

#rs.get_n_splits(X)
for train_index, test_index in rs.split(XX):
    print("TRAIN:", train_index, "TEST:", test_index)
    
#note the split is random after shuffling

TRAIN: [1 3 0 4] TEST: [5 2]
TRAIN: [4 0 2 5] TEST: [1 3]
TRAIN: [1 2 4 0] TEST: [3 5]
TRAIN: [3 4 1 0] TEST: [5 2]
TRAIN: [3 5 1 0] TEST: [2 4]


In [26]:
rs = ShuffleSplit(n_splits=5, train_size=0.5, test_size=.2, random_state=0)
#trainsize : .5*6 = 3
#test size: .2*6=1.2
for train_index, test_index in rs.split(XX):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [1 3 0] TEST: [5 2]
TRAIN: [4 0 2] TEST: [1 3]
TRAIN: [1 2 4] TEST: [3 5]
TRAIN: [3 4 1] TEST: [5 2]
TRAIN: [3 5 1] TEST: [2 4]


---

In [27]:
#Grid SearchCV

In [28]:
knn.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': -1,
 'n_neighbors': 3,
 'p': 2,
 'weights': 'uniform'}

In [29]:
k = np.arange(1, 50, 2)

In [30]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors': k}
grid = GridSearchCV(knn, param_grid=param_grid, cv = 5, scoring = 'accuracy', n_jobs = -1, verbose = 0)
#Most common scoring techniques on accuracy, precision, recall, f1, roc_auc

In [31]:
grid.fit(X_train, y_train)

C:\Users\Vaibhav\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=-1,
                                            n_neighbors=3, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [32]:
grid.best_params_ #best parameter

{'n_neighbors': 9}

In [33]:
grid.best_score_ #Accuracy score for the best model 
#make the prediction on test data

0.9523809523809523

In [34]:
ypred = grid.predict(X_test)
ypred

array([0., 0., 2., 0., 0., 2., 0., 2., 2., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 2., 1., 1., 1., 2., 1., 1., 0., 0., 2., 0., 2., 2., 0., 1., 2.,
       1., 0., 2., 1., 1., 2., 1., 1., 2., 1., 0.])

---

### Cross Validation using cross_val_score

In [35]:
from sklearn.model_selection import cross_val_score

In [36]:
X.head(3)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [37]:
y[:4]

0    0.0
1    0.0
2    0.0
3    0.0
Name: Species, dtype: float64

In [38]:
cross_val_score(estimator = grid, X=X, y = y, cv= 5, scoring= "accuracy" )
#use grid or knn

array([0.93333333, 1.        , 0.93333333, 0.96666667, 1.        ])

In [43]:
cross_val_score(estimator = grid, X=X, y = y, cv= kf, scoring= "accuracy" )

array([1.        , 0.93333333, 1.        , 0.96666667, 0.93333333])

In [49]:
# instantiate the classifier
skf_results =  cross_val_score(estimator=knn, X=X, y=y, cv=skf, scoring='accuracy')

---

### Cross Validation using Cross Validate
used incase we want to evaluate multiple scoring techniques

In [50]:
from sklearn.model_selection import cross_validate
#incase we want to evaluate multiple scoring techniques

In [51]:
scoring = { "acc": "accuracy", 
           "prec": "precision_macro",
           "f1": "f1_micro" #formula same as accuracy, hence the values are exactly same
          }
#we need to use averaging techniques: macro / micro / weighted for multi-classification - for unbalanced dataset use micro or weighted average
#for binary problems use binary averaging techniques: f1, precision, recall,roc_auc
#for regression problems: use 'neg_mean_absolute_error', 'neg_mean_squared_error', 
#'neg_median_absolute_error', r2



#Various possible scoring techniques:
#['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 
#'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 
#'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'mutual_info_score', 
#'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error',
#'neg_median_absolute_error', 'normalized_mutual_info_score', 'precision', 'precision_macro', 
#'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'recall', 'recall_macro', 
#'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'v_measure_score']

In [52]:
scores = cross_validate(estimator = knn, X=X, y=y, cv= kf, scoring=scoring, return_train_score=True)
scores #return_train_score will also return train accuracies

{'fit_time': array([0.00499582, 0.00699377, 0.00599575, 0.00599551, 0.00799441]),
 'score_time': array([0.10693431, 0.06695795, 0.06995821, 0.06795835, 0.07195425]),
 'test_acc': array([1.        , 0.93333333, 1.        , 0.96666667, 0.93333333]),
 'train_acc': array([0.95      , 0.96666667, 0.95      , 0.975     , 0.98333333]),
 'test_prec': array([1.        , 0.93333333, 1.        , 0.97619048, 0.93333333]),
 'train_prec': array([0.95238095, 0.96602564, 0.94987469, 0.97407407, 0.98351648]),
 'test_f1': array([1.        , 0.93333333, 1.        , 0.96666667, 0.93333333]),
 'train_f1': array([0.95      , 0.96666667, 0.95      , 0.975     , 0.98333333])}

In [53]:
scores = cross_validate(estimator = knn, X=X, y=y, cv= 5, scoring=scoring, return_train_score=True)
scores

{'fit_time': array([0.0059967 , 0.00399661, 0.00299716, 0.00299811, 0.00399637]),
 'score_time': array([0.07395267, 0.07995367, 0.05796337, 0.0599618 , 0.05296922]),
 'test_acc': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ]),
 'train_acc': array([0.95833333, 0.95833333, 0.96666667, 0.96666667, 0.95      ]),
 'test_prec': array([0.96969697, 0.96969697, 0.94444444, 0.96969697, 1.        ]),
 'train_prec': array([0.95851574, 0.95851574, 0.96741855, 0.96666667, 0.95      ]),
 'test_f1': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ]),
 'train_f1': array([0.95833333, 0.95833333, 0.96666667, 0.96666667, 0.95      ])}

In [54]:
scores = cross_validate(estimator = knn, X=X, y=y, cv= skf, scoring=scoring, return_train_score=True)
scores

{'fit_time': array([0.00599432, 0.00299811, 0.00600004, 0.00299716, 0.00399756]),
 'score_time': array([0.06196189, 0.05596519, 0.05396318, 0.05596471, 0.05496597]),
 'test_acc': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ]),
 'train_acc': array([0.95833333, 0.95833333, 0.96666667, 0.96666667, 0.95      ]),
 'test_prec': array([0.96969697, 0.96969697, 0.94444444, 0.96969697, 1.        ]),
 'train_prec': array([0.95851574, 0.95851574, 0.96741855, 0.96666667, 0.95      ]),
 'test_f1': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ]),
 'train_f1': array([0.95833333, 0.95833333, 0.96666667, 0.96666667, 0.95      ])}

---