In [27]:
#Demonstrate Simple Linear Regression
#Use-case: Create a model to predict the salary of the employee 
#based on his/her years of experience.

In [28]:
#Import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
#Import the dataset
dataset = pd.read_csv('C:\\Users\\Vaibhav\\Desktop\\BA\\Datasets\\Salary_Data.csv')
dataset.head(3)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0

In [30]:
#Seperate the features and label
features = dataset.iloc[:,[0]].values
label = dataset.iloc[:,[1]].values

In [31]:
#Seperate the data as Training set and Testing set
#Training set is responsible to cretae the model/train the model
#Testing set is responsible to evaluate the model. (To test the accuracy of the model)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=10)

In [32]:
#Create the model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
#Train my model using X_train(feature set),y_train(label set)
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
model.intercept_

array([26089.09663242])

In [34]:
model.coef_

array([[9356.86299354]])

In [35]:
# salary = 26089.09663242 + 9356.86299354 * (YearExperience)

In [36]:
#Testing/Evaluating the model
y_prediction = model.predict(X_test)

In [37]:
y_prediction

array([[89715.76498848],
       [56031.05821174],
       [53223.99931368],
       [40124.39112273],
       [44802.8226195 ],
       [92522.82388655]])

In [38]:
y_test

array([[91738.],
       [54445.],
       [56642.],
       [37731.],
       [43525.],
       [98273.]])

In [39]:
#Check the accuracy score (R2)
model.score(X_test,y_test)

0.9816423482070255

In [40]:
#Another method to check the R2 score
from sklearn.metrics import r2_score
r2_score(y_test,y_prediction)

0.9816423482070253

In [41]:
import pickle

In [42]:
pickle.dump(model,open("SimpleLRModel.model",'wb'))
#wb means write in non-truncated mode